### ISSUE TITLE
Demo Always fails.

### ISSUE THREAD

**Issue by toddmcbrearty** [RobThree/TwoFactorAuth#1]
I've copied the demo into a laravel 5.1 view. 
Every time i load the page i get this line
```
When aforementioned code (893875) was entered, the result would be: FAIL
```
Obviously each time i refresh the code changes but it still fails. Only change i made in the demo was to remove 
```
require_once 'loader.php';
Loader::register('../lib','RobThree\\Auth');
```
Since laravel will load the package.

**Comment by toddmcbrearty** [comment]
I believe i found the problem.
In the demo you have 
```
($tfa->verifyCode($secret, $code) === true)
```
verifyCode function returns 0 or 1 so that would obviously fail is it's not exactly equal to true. 
You can either change === to == or i think it's better to return verifyCode as a bool
```
return (bool) result
```

**Comment by RobThree** [comment]
Was just looking into it; verifyCode should return a bool. Will fix in a few minutes.

**Comment by toddmcbrearty** [comment]
great! thanks.

**Comment by toddmcbrearty** [comment]
if it's easier for you i can do a pull request

**Comment by RobThree** [comment]
https://github.com/RobThree/TwoFactorAuth/commit/e837caa9ced98c86ba1b5d6af66e94532fc06ef0

I'll create a new release.
Thanks for reporting it! :+1:

**Comment by DanieleSassoli** [comment]
Hi, this got me confused this morning, luckly I saw this issue... I installed the package from composer (`composer require robthree/twofactorauth`) and it installed version 1.1, I tried telling composer to install version 1.2(which fixes this issue), with `composer require robthree/twofactorauth:1.2`  but composer stated that it coulnd't find any versione with that `The requested package robthree/twofactorauth 1.2 could not be found.`. I can't see what I'm doing wrong so maybe there's some sort of problem with the release...

**Comment by RobThree** [comment]
Whoops... forgot to update composer.json. I have created a new release 1.3 which should work (probably should've been a minor 1.2.1 or something but what the hell... :stuck_out_tongue_winking_eye: )

**Comment by DanieleSassoli** [comment]
yep, fixed, thank you...

**Comment by RobThree** [comment]
:+1:
