### ISSUE TITLE
QR Code Expiring

### ISSUE THREAD

**Issue by DavidWarnerDW** [RobThree/TwoFactorAuth#100]
We have a website using this library for 2FA, the QR code expires exactly two months from when it was first scanned by the authenticator app. This occurs using both Authy and Google Authenticator. Do you have any ideas why this is occurring or is it the web site? Appreciate it if you or someone else could let us know asap.

**Comment by willpower232** [comment]
I'm not sure what you mean, the QR code is of the two factor secret and the secret should be attached to the users account and then recorded into the users device to generate the code.

I don't believe this library adds any kind of expiration to that process, it doesn't make sense to cut off or reset a users two factor unless they have lost access to their device.

**Comment by valerio-bozzolan** [comment]
Probably this can be closed, until additional feedback is added.
