### ISSUE TITLE
CodeIgniter 4 Integration

### ISSUE THREAD

**Issue by glewe** [RobThree/TwoFactorAuth#107]
Hi Rob,
thanks for your work on this library.
I just wanted to let you know that I published a CodeIgniter 4 authentication module in which I integrated your TwoFactorAuth project.
[https://github.com/glewe/ci4-auth](https://github.com/glewe/ci4-auth)
Maybe you want to add that to the readme in the Integrations section.
Best regards,
George

**Comment by willpower232** [comment]
Make a PR if you like

**Comment by RobThree** [comment]
I agree, make a PR and we'll be happy to merge.
