### ISSUE TITLE
demo for verifyCode()

### ISSUE THREAD

**Issue by GhostCyborg** [RobThree/TwoFactorAuth#11]
Hello, could you possibly create a demo for how to use verifyCode(), for example, a login page of some sort? I'm not very experience with PHP, and don't quite understand how to do this, and when running the command 'php composer.phar require robthree/twofactorauth', I get the error 'Could not open input file: composer.phar', is it suppose to be composer.json?

**Comment by RobThree** [comment]
Maybe have a look in the [demo](https://github.com/RobThree/TwoFactorAuth/tree/master/demo) folder?

**Comment by RobThree** [comment]
For support on composer you should read the conposer docs / use their support channels.

**Comment by GhostCyborg** [comment]
Yes, but the demo folder doesn't really say anything about verifying the authentication token, only on how to generate one

**Comment by RobThree** [comment]
It also demonstrates verifyCode?
Just pass the secret and the user-entered code and it will return true when it checks out, false otherwise.

**Comment by RobThree** [comment]
Also, step 3 of the README explains using verifyCode().

**Comment by GhostCyborg** [comment]
@RobThree Thank you for your quick responses, it was my fault for not noticing that it **did** actually veritfy the code, Thanks! :)

**Comment by RobThree** [comment]
:+1:
