### ISSUE TITLE
QR Code doesn't work with Dashlane

### ISSUE THREAD

**Issue by DarkShoro** [RobThree/TwoFactorAuth#112]
While Google Authenticator and Authy are able to scan and use the QR Code just fine, something in the secret make Dashlane not be able to scan it.

Any idea of why?

**Comment by RobThree** [comment]
Unfortunately my crystal ball is out for repairs, so you'll have to fill us in into some of the details. What are the parameters you're creating the QR code with for example, so that we can try to reproduce and have a look at your actual values and see if there's something wrong with them.

**Comment by DarkShoro** [comment]
I'm creating the QR Code with nothing else than the default parameters, also using default parameters for the 
`new TwoFactorAuth();`

It's nothing but default.

**Comment by RobThree** [comment]
Could you show us a QR code that doesn't work? Or the DataUri?

**Comment by DarkShoro** [comment]
The problem is kinda solved by itself.

There is two methods of adding a 2FA code on Dashlane, one of them don't work, but the other do, so it's not a you problem.

**Comment by RobThree** [comment]
Could you elaborate on what the two methods are and which of them works? For future reference...

**Comment by DarkShoro** [comment]
If you go to the "Authenticator" page and click "Add a 2FA token", then scan the QR Code, the reading will fail and Dashlane will spill out an error

If you, however, go to your existing IDs, click the one from your website, edit it, and click "SETUP" on the 2FA part, then, the code will scan fine and be added to your account.

I hope I was clear enough.

**Comment by RobThree** [comment]
That's _really_ weird.

Would you mind sharing a (test) QR code with us so we can (try to) reproduce?

**Comment by DarkShoro** [comment]
Here is one of the QR code generated

![image](https://github.com/RobThree/TwoFactorAuth/assets/62524520/f89706c2-dd83-4d51-9fac-4730cfe046bd)

**Comment by RobThree** [comment]
It scanned fine for me, first try? Deleted it, scanned it again, no problem. Are we talking iOS, Android?

**Comment by DarkShoro** [comment]
I am talking Android, two of my friend plus me couldn't scan it in the "Authenticator" tab, but editing our profile with our existing info, then scanning the code there worked for us.

**Comment by RobThree** [comment]
I'm sorry, that _must_ be a Dashlane issue then. It scans perfectly fine for me on iOS. Maybe someone else can chime in?

**Comment by willpower232** [comment]
seems fine for me, the URI encoded in the qr code looks fine too, you can use the Google Authenticator app to test it out with a different app on the same phone without having to set up a whole new account to confirm.
