### ISSUE TITLE
Incompatible with endroid/qr-code > 5.0.0

### ISSUE THREAD

**Issue by Mattie112** [RobThree/TwoFactorAuth#114]
When using this project with endroid/qr-code version 5.0.2 I get the following error:

```
Exception {"message":"Class \"Endroid\\QrCode\\ErrorCorrectionLevel\\ErrorCorrectionLevelHigh\" not found"} 
```

```
            $qr_provider = new EndroidQrCodeProvider();
            $tfa = new TwoFactorAuth(issuer: "xx", qrcodeprovider: $qr_provider);
            $qr = $tfa->getQRCodeImageAsDataUri("uid", $secret);
```
With version 4.8.5 it works just fine.

**Comment by willpower232** [comment]
I guess this line doesn't work for version 5 then?

https://github.com/RobThree/TwoFactorAuth/blob/137df4dd3cd998e7096705cd0b3aed17b4c25d53/lib/Providers/Qr/EndroidQrCodeProvider.php#L31

Definitely open to PRs on this one.

**Comment by Mattie112** [comment]
I will try to see if that is the only problem and then create a PR for this! if it is more work I dont have time right now and I will report back.

**Comment by Mattie112** [comment]
This should fix it: https://github.com/RobThree/TwoFactorAuth/pull/115

Don't currently have the time to test it with other versions then 4 and 5.

**Comment by Mattie112** [comment]
Thanks, I will update to the latest version and confirm that it works. Thans for adding the test/build config, did not notice that :)

**Comment by Mattie112** [comment]
Yes, all seem to be working fine (with Endroid v5).

Great timing btw, I was just about to merge my internal MR but now I can set it back to this repo instead of my own fork :)

Thanks again!
