### ISSUE TITLE
Source folder as "src"

### ISSUE THREAD

**Issue by lguima** [RobThree/TwoFactorAuth#12]
As convention for packages using PSR-4, the source folder should be named "src", shouldn't?

**Comment by RobThree** [comment]
I have \*no\* idea. I'm not much of a PHP developer so I would like to get some more opinions on this (and your PR #13 . Maybe @anvyst who did PR #10 can answer this?

**Comment by anvyst** [comment]
@lguima , yes it has to, but my concern of not breaking the backward compatibility was to use initial `lib` directory as it is. `lib` directory still should work fine.

**Comment by lguima** [comment]
Understood, thanks @anvyst! You too @RobThree!

**Comment by RobThree** [comment]
So... we leave it as is? Or...?

**Comment by anvyst** [comment]
@RobThree , it's up to you. If you're willing to keep the code  PSR-0 compatible then it's better to rename it. PSR-4 is more flexible, at least I couldn't find any references to strict directory namings in docs.

> The "src" and "tests" directories have to include vendor and package directory names. This is an artifact of PSR-0 compliance. [PSR-4 FIG](http://www.php-fig.org/psr/psr-4/meta/)

**Comment by RobThree** [comment]
I don't know which PSR I should 'aim for'? I don't know if I want to be "as much PSR's as possible" or "highest PST possible" or... 
Again, not (much of) a PHP-guy so this whole PSR stuff is pretty confusing...

**Comment by anvyst** [comment]
@RobThree, that sounds like a good reason of keeping the things as they are :)

**Comment by klaude** [comment]
> I don't know which PSR I should 'aim for'? I don't know if I want to be "as much PSR's as possible" or "highest PST possible" or...
> Again, not (much of) a PHP-guy so this whole PSR stuff is pretty confusing...

PSR-0 was the Framework Interoperability Group[1]'s first go at an auto-loading standard. It was deprecated in favor of PSR-4 which is a bit easier to implement. PSRs should be treated as recommended best practices. Most larger frameworks, framework components, and libraries tend to adhere to them. It's not the end of the world if code is in `src/` vs `lib/` or changes between the two. Consumers of the library wouldn't notice the change. I don't think that either PSR-0 or PSR-4 say what the directory name for a namespace root should be, just that there should be one. 

Personally I like to keep my code as PSR compliant as possible. I can't fault those that choose not to follow them. Not following some of the PSRs, like the autoloader or logger specs, may make it harder for users to consume your library. In the end they're just recommendations.

[1] The FIG is comprised of members from larger frameworks and projects in the PHP community. They're largely responsible for PHP becoming much less of a "wild west" kind of language in recent years. Some of the PSRs like PSR-0/4 and PSR-7 are very widely adopted, while some like the PSR-2 code standard are used when it's comfortable for the author.
