### ISSUE TITLE
minimal version

### ISSUE THREAD

**Issue by f1-outsourcing** [RobThree/TwoFactorAuth#132]
I am not really a developer and thought about adding your library somewhere. But all these files for simple qr code generation and auth seems a bit over done. 

As you write on your readme it does not really make much sense to remote generate your qr codes. So why even offer this? When I was browsing your files I see also things like time.google.com. Anyone with a bit of security has blocked the major clouds.

- does your library even work in a air-gapped environment?
- is there some minimal download, that just does basic things off line? No google crap, no remote access crap. just the basics.

**Comment by RobThree** [comment]
If you don't like it you don't _have_ to use it. I don't mind criticism or constructive feedback but your approach isn't very pleasant to put it mildly. And that's coming from a Dutch guy which are known for being blunt.

**Comment by NicolasCARPi** [comment]
Hello,

Version 3.x (currently the `master` branch) adresses these issues you mention. In v3, one needs to explicitely define a QRCodeProvider.

You can use Endroid or Bacon, or anything else, as long as the interface works (I'm using Mpdf QR code generator in my project). These work perfectly in air-gapped systems.

We're in the process of releasing v3.

> But all these files for simple qr code generation and auth seems a bit over done.

A lot of my recent contributions removed some code, and streamlined the library. For instance, this PR https://github.com/RobThree/TwoFactorAuth/pull/122.

As a final note, please realize that your message is quite negative and out of place. This library is provided to you free of charge, and while we welcome constructive criticism, your message is too blunt. Look at how you could have expressed the same thing but with respect: https://github.com/RobThree/TwoFactorAuth/issues/104.
