### ISSUE TITLE
QrCodeProvider is being set as the issuer?

### ISSUE THREAD

**Issue by LordAlderaan** [RobThree/TwoFactorAuth#138]
When I try to display a QR code of the secret using 
`<img src="<?php echo $tfa->getQRCodeImageAsDataUri('Bob Ross', $secret); ?>">`

I get the following error

`Object of class RobThree\\Auth\\Providers\\Qr\\EndroidQrCodeProvider could not be converted to string in /var/www/html/bla/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php:275`

I did some searching and I think it's because I use the following to create a new $tfa object:
`$tfa = new TwoFactorAuth(new EndroidQrCodeProvider());`

I took this from the [getting started](https://github.com/RobThree/TwoFactorAuth/blob/master/docs/getting-started.md) page. However, this seems to be setting the QrCodeProvider as the issuer of the object.

When I create the new $tfa object like this it does work:
`$tfa = new TwoFactorAuth('fakeissuer',6,30,'sha1',new EndroidQrCodeProvider());`

I would prefer not to have to manually provide the digits, period and algorithm but I don't know if this is a bug, a documentation issue or something with my setup. 

Full error:
`[Fri Sep 20 11:27:01.949706 2024] [php7:error] [pid 18244:tid 18244] [client 192.168.192.5:53204] PHP Fatal error:  Uncaught Error: Object of class RobThree\\Auth\\Providers\\Qr\\EndroidQrCodeProvider could not be converted to string in /var/www/html/bla/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php:275\nStack trace:\n#0 /var/www/html/bla/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php(207): RobThree\\Auth\\TwoFactorAuth->getQRText()\n#1 /var/www/html/bla/temp/totp.php(15): RobThree\\Auth\\TwoFactorAuth->getQRCodeImageAsDataUri()\n#2 {main}\n  thrown in /var/www/html/bla/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php on line 275`

php info:
`PHP 7.4.33 (cli) (built: Apr 12 2024 00:02:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
`

**Comment by willpower232** [comment]
The docs refer to the latest version of the library, sounds like you need to update.

**Comment by NicolasCARPi** [comment]
Make sure to update your PHP version too! ;)

**Comment by RobThree** [comment]
> I would prefer not to have to manually provide the digits, period and algorithm but I don't know if this is a bug, a documentation issue or something with my setup.

(Replying from my phone)
Thanks @willpower232 and @NicolasCARPi for answering. Not much to add except: you should be able to specify only the arguments you want by using [named arguments](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments).

**Comment by willpower232** [comment]
I was about to say haha, sounds like you have more things you should updated :sweat_smile: 

Named arguments are PHP 8.0 so you don't have to go all the way to 8.2 (although you definitely should :pray: )

**Comment by LordAlderaan** [comment]
Yes, certainly not best practices haha

In my defense it's a non-internet facing non-dtap machine purely for experimentation ^_^
