### ISSUE TITLE
Question about how to validate the code generated in Google Authenticator

### ISSUE THREAD

**Issue by ederlucaace** [RobThree/TwoFactorAuth#139]
Good morning

I am starting the two-factor authentication process on my website. I confess that this is the first time I have dealt with this technology. Using the examples mentioned in the project demo, I was able to generate the QR code and the manual key. In my case, Google Authenticator recognized both and the authentication token is being generated. My question is: how do I authenticate this code and check whether it is valid or not? Is there a function within the library that validates the token that is generated from time to time by Google Authenticator?

**Comment by willpower232** [comment]
You would need to use the verifyCode function to compare the user input with the previously stored secret (and optionally some time arguments if you're going in deep)

https://github.com/RobThree/TwoFactorAuth/blob/ab4c33007f1e7be632ffc8374613ae87bd60f83d/lib/TwoFactorAuth.php#L85

**Comment by ederlucaace** [comment]
thanks it worked perfectly
