### ISSUE TITLE
EndroidQrCodeProviderWithLogo v6

### ISSUE THREAD

**Issue by YellowMaker** [RobThree/TwoFactorAuth#142]
I see fix for EndroidQrCodeProvider (https://github.com/RobThree/TwoFactorAuth/issues/141, https://github.com/RobThree/TwoFactorAuth/pull/140) but what about EndroidQrCodeProviderWithLogo class?

**Comment by willpower232** [comment]
It extends the original one so should be mostly working, are you seeing any specific error messages?

**Comment by YellowMaker** [comment]
```
Fatal error:  Uncaught Error: Call to undefined method Endroid\QrCode\Logo\Logo::create() in /var/www/composer/vendor/robthree/twofactorauth/lib/Providers/Qr/EndroidQrCodeWithLogoProvider.php:36
  thrown in /var/www/composer/vendor/robthree/twofactorauth/lib/Providers/Qr/EndroidQrCodeWithLogoProvider.php on line 36
```

**Comment by YellowMaker** [comment]
This should work https://github.com/RobThree/TwoFactorAuth/pull/143

**Comment by willpower232** [comment]
Thanks for the PR! Released now.
