### ISSUE TITLE
Make IQRCodeProvider parameter optional

### ISSUE THREAD

**Issue by KlaasBonnema** [RobThree/TwoFactorAuth#144]
Most of the time you will instanciate TwoFactorAuth to verify a submitted OTP value. 
Only when a new authenticator link is to be setup you will also need a QR Code provider. You will most likely go a different path or even use a different module for this.
We now always need to instanciate a QR Code provider which is a waste of resources.
Please make this parameter optional or at least provide a dummy provider.

**Comment by RobThree** [comment]
This makes sense; I think we could consider a 'default' QR Code provider that just throws (with a _clear_ message that we're in "validation mode only" or something) or, indeed, make it optional and throw in the `getQRCodeImageAsDataUri` method when we don't have a QR Code provider.

Another route would be to split the `TwoFactorAuth` class into a "verifier" and "creator" but that would require more work and a lot of breaking changes.

@willpower232 / @NicolasCARPi what is your opinion on this?

**Comment by willpower232** [comment]
I'm not sure I see the point, the extra resources only add up to a couple of dozen lines of code and complicating your application to load this library in two variants probably adds up to the same difference.

Frameworks promote using service containers to resolve using third party libraries so there should not need to be a duplication of the code required to instantiate and you don't need to duplicate the QR code provider configuration wherever you use the library.

It is hard to think of an application which doesn't need a QR code representing the two factor secret at some point.

**Comment by RobThree** [comment]
@willpower232 You make an excellent point on the service container. Although I do think "newing up" a QR code provider only to verify an input is a waste of CPU cycles, making it optional would complicate matters as well. A dummy QR code provider is easily implemented though.

A split in 'creator' and 'verifier' was a brainfart I didn't think through enough; consider that idea never even existed.

**Comment by NicolasCARPi** [comment]
I also don't think it's worth the hassle, and agree with @willpower232. Also, IMHO, an instanciated object must be ready to do everything. If we make this parameter optional we could not catch the bug of instantiating it without it and then trying to get a QR code.

Another approach is to pass the qr provider to the qr code generating method, instead of the constructor. But it's not great and not something I'd want to see.

Things are fine as they are, this is a non-problem and this issue should be closed.
