### ISSUE TITLE
Andere code in "Google Authenticator" app 

### ISSUE THREAD

**Issue by J3Sta216** [RobThree/TwoFactorAuth#16]
Ha Rob,

Ik probeer jouw TwoFactorAuth te gebruiken. Ik krijg een QR-code die scan in met de app "Google Authenticator" maar op het moment dat ik `$tfa->getCode($secret);` doe krijg ik een andere code te zien dan op mijn app. Op mijn server is NTP enabled. Enig idee wat hier fout gaat?

Mvg,
Jeroen

**Comment by RobThree** [comment]
> Op mijn server is NTP enabled.

Maar de tijd is ook gecontroleerd en correct? Tijdzone is ook correct ingesteld?

**Comment by J3Sta216** [comment]
We hebben twee tijden, "server tijd" en "code tijd", server tijdzone staat op Etc/UTC (UTC, +0000) maar de "code tijd" staat wel juist ingesteld, dus op het moment dat ik `echo time();` doe krijg ik de juiste tijd terug, als ik `$code = $tfa->getCode($secret, time());`of `$code = $tfa->getCode($secret);` doe, maakt dit geen verschil.

**Comment by RobThree** [comment]
> dus op het moment dat ik echo time(); doe krijg ik de juiste tijd terug

Dat is dan dus UTC tijd? M.a.w.: op het moment is het UTC 15:69, ofwel 16:59 onze tijd. Dat klopt als je de output van `time()` door, zeg, http://www.epochconverter.com/ haalt?

**Comment by J3Sta216** [comment]
Bedankt voor de informatie, het is gelukt, ik moest inderdaad de `time()` functie een uur terug zetten.

**Comment by RobThree** [comment]
Je kunt vanaf nu de `ensureCorrectTime()` methode aanroepen om te controleren of de juiste tijd gebruikt wordt. Zie ook [Time providers in de README](https://github.com/RobThree/TwoFactorAuth#time-providers)
