### ISSUE TITLE
Bit size used

### ISSUE THREAD

**Issue by michaelcowell** [RobThree/TwoFactorAuth#17]
Hey @RobThree ,

Thanks for taking the time to write this library.

Can I ask if there's a reason RFC 4226's recommendation of 160 bits isn't used as the default value?

Ref: https://tools.ietf.org/html/rfc4226#section-4

**Comment by RobThree** [comment]
Yes, the reason is it was primarily intended for Google Authenticator and it uses (used?) 80 bits by default so it seemed reasonable to default to 80 bits as well:

http://security.stackexchange.com/a/47554/3992
https://github.com/google/google-authenticator/issues/340

It's just a default though and you can override the value to whatever (supported!) value you want 😉 Some authenticators (LastPass Authenticator, Authy, Google Authenticator, ...) may or may not support those values so you should test for the intended use!

**Comment by michaelcowell** [comment]
Hey Rob, thanks for the quick response.

I usually use Google Authenticator so I just went ahead and tested:

* Google Authenticator
* FreeOTP
* LastPass Auth
* Authy

And all seem to support 160 bit secrets. Unless I'm missing something, wouldn't it be best to set the default higher?

**Comment by RobThree** [comment]
As [this post](http://security.stackexchange.com/a/47554/3992) points out, I don't think it's *that* important to change the default value (and possibly break other clients or backward compatibility). If you think it's ok for your usecase then simply pass a different value to `createSecret()`.

That's not to say I'm not willing to change the default, and I even agree a higher value would be better, but I also don't want to cause problems for people currently depending on the default value; in this way it's a breaking change. It's just that I don't want to change this on a whim / take it lightly. If anything: before changing the default value I'd like to do some kind of 'poll' to find out all in favor against all against.

**Comment by michaelcowell** [comment]
Hey,

Yeah, I can see the case against it being a technically infeasible problem, though if it wasn't for the backwards compatibility issues I think it should still be changed.

Maybe as a way to promote this without breaking anything we could modify `demo.php` and `README.md` to supply 160 with a comment explaining why?

**Comment by RobThree** [comment]
You're welcome to make a PR; if not then I'll get to it myself sometime this week I think.

**Comment by RobThree** [comment]
In 5093ab230cd8f1296d792afb6a49545f37e7fd5a I changed the demo and README to advise a 160+ bits secret (amongst some other changes).

**Comment by michaelcowell** [comment]
👍
