### ISSUE TITLE
Everything works fine until I change qrcode provider as suggested....

### ISSUE THREAD

**Issue by WorkAppLL** [RobThree/TwoFactorAuth#22]
Does anyone have idea what could be wrong ?
I've downloaded phpqrcode.php saved it into same directory as 2factorauth as suggested , saved myprovider.php as suggested but getting error 

Fatal error: Interface 'RobThree\twofactorauth\lib\Providers\Qr\IQRCodeProvider' not found in C:\xampp\htdocs\loginsystem\security.php on line 8

Any suggestion much appreciated!

Luka

**Comment by jackttcoms** [comment]
I'd recommend this it works very well

https://www.codester.com/items/4267/2-step-authentication-php-script?ref=ChewiScripts

**Comment by RobThree** [comment]
> Any suggestion much appreciated!

It seems somehow your class isn't loaded correctly; I don't think that is a problem with this library though.

**Comment by WorkAppLL** [comment]
Thanks, you are right, problem solved!
