### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by HarmJan1990** [RobThree/TwoFactorAuth#23]
Keep getting this fatal error:

Fatal error: Uncaught Error: Class 'RobThree\Auth\Providers\Rng\CSRNGProvider'

Installed trough composer 3 times on different machines.

**Comment by RobThree** [comment]
`Fatal error: Uncaught Error: Class 'RobThree\Auth\Providers\Rng\CSRNGProvider'`

That seems to be only part of an error? What version are you using?

**Comment by jackttcoms** [comment]
https://www.codester.com/items/4267/2-step-authentication-php-script?ref=ChewiScripts This seems reliable and has good reviews
