### ISSUE TITLE
QR image is truncated

### ISSUE THREAD

**Issue by phiara** [RobThree/TwoFactorAuth#25]
Hello,

do you have any idea why the generated QR code is being truncated?
See the image attached.

Where should I look in your code to check the height?

Let me know if you need additional info.

Thanks.

![qrgen](https://user-images.githubusercontent.com/11851450/33527809-b49b0782-d85f-11e7-94a2-2db79759ee6c.png)

**Comment by RobThree** [comment]
You solved the issue yourself? Was the issue with this lib or something else?

**Comment by phiara** [comment]
I'm pretty sure the problem was on my end. After a few retries, the QR images were being generated successfully. Thank you for your code by the way, it's awesome! 👍
