### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ukitconsultant** [RobThree/TwoFactorAuth#26]
Hi there, 

I'm getting the following; 

Fatal error: Class 'RobThree\Auth\TwoFactorAuth' not found in /[REMOVED]/public_html/2fa.php on line 12

`
	
       <?php
        error_reporting(-1); 
        ini_set('display_errors', 1);

         require_once '2fa/demo/loader.php';
        Loader::register('2fa/lib','RobThree\\Auth');
        
        use \RobThree\Auth\TwoFactorAuth;
        
        $tfa = new TwoFactorAuth('MyApp');
		
		// Generate the code, store it inside the database, 
		// and generate the QR code for the user to scan, or provide the code
		// for the user to manually type into the app being used.
		
		// Generate User Image
		$secret = $tfa->createSecret(160);
		
	echo "Two Factor Authentication Platform<br /><br />";
		echo "Secret Generated: " . $secret;
		echo "<br /><br /><br />";
		echo "Code for App: " . chunk_split($secret, 4, ' ');`

**Comment by RobThree** [comment]
Are the files where they are supposed to be? Do the files have the correct permissions? What have you tried to troubleshoot this problem yourself?

**Comment by ukitconsultant** [comment]
Yes, yes and I’ve tried them in different locations, on five separate servers with the same end result.

Many Thanks,

Mr. Christopher S. East MBCS

Serves As;
Honorary Secretary
Internet Specialist Group
https://u4755625.ct.sendgrid.net/wf/click?upn=dRHYQCJokGWz7dUM0PuPveTdqjhkbtlmYeume7kRLeg-3D_s5UH8bhnBaopYjthcNSRcV8fLxcQwIkhqkSOaCfZhkFF6iOKVz8WSrmwyg60of-2FUyh3IF9pUad6ejuWx1IaMl6w6Ko5-2B0iaOB-2FddzGmXkmAwvVNZnYIpM0i3YKTSIZ3oxBPJ8zEaaVjRm68DCPdP9TXOmf64llanvCs7bHXr6hvkGP9Sb5hGa0bVFP4AVBBgaY87EHH9vKvu-2FxHyDt9QjbPegzr-2FJSEI0bkDpaykFipy7uQeiyvRq-2FrORGwnS1Dh8Gxkd-2Fr9He-2BBUoqYHkHj8wBS0vCHAq0BODVRbHQhK2wRUldZtpLAhfnhfpu-2BpHpEyGHWZIeEblFVuEzKwJTY5Q-3D-3D

Secretary & Broadcasting and Recording
BCSWomen Specialist Group
https://u4755625.ct.sendgrid.net/wf/click?upn=hj0MEI9pdapxV92WbYNsB2eoOP6dpbPXuDwioZnUr1o-3D_s5UH8bhnBaopYjthcNSRcV8fLxcQwIkhqkSOaCfZhkFF6iOKVz8WSrmwyg60of-2FUyh3IF9pUad6ejuWx1IaMl6w6Ko5-2B0iaOB-2FddzGmXkmAwvVNZnYIpM0i3YKTSIZ3oxBPJ8zEaaVjRm68DCPdP9TXOmf64llanvCs7bHXr6hvkGP9Sb5hGa0bVFP4AVBBgOnJb6-2BzDXHQmENGz-2B56DLIJg00mVRzdPLbj57P5-2BH1ATZY5uq4gHZm6cecZG8GuHs1woFsdze8libJo1gQfS-2FSMFBAWmTEYW6V-2BSL2qhuyTdgMBbdGR4Jljs1eckDbAqkV1wVkfBuhd51fTHGVx-2FHw-3D-3D

Chartered Institute for IT
(Also known as the British Computer Society)

E: christopher.east@bcs.org<mailto:christopher.east@bcs.org>
T: +44 (0) 7490 079276
T: +44 (0) 20 7112 8120

This email is private and confidential, and should only be viewed by the addressee. If you are not the addressee then please let the sender know and remove all copies of this message from your email system.

This email has been sent from a mobile device. It may therefore contain errors or omissions. If you believe this error to contain an error or omission then please contact the sender.

No responsibility is accepted for any damage or loss of any type as a result of this email, there are many virus and spam protection systems available to suit every budget including no budget, so there really is no excuse.

Thank before you print! Do you really need to print this email message? Help save the environment for everyone by keeping it digital.

On 31 Dec 2017, at 02:48, Rob Janssen <notifications@github.com<mailto:notifications@github.com>> wrote:


Are the files where they are supposed to be? Do the files have the correct permissions? What have you tried to troubleshoot this problem yourself?

**Comment by willpower232** [comment]
Evidently `Loader::register()` is not locating or including the appropriate PHP files from this library.

Is it from a particular framework? You should review the documentation or the code itself to see where you should put the files.

**Comment by ukitconsultant** [comment]
Yep, I got that far on my own, the why is the issue.

I’m running it outside of any framework, just a singular php file calling the code which was copied from the demo file, and then altered two loading filepaths to suit the correct file paths on the various file systems, each one produced the same error. I retrieved it using the latest version of composer in each case, and have run file comparisons between the files retrieved in different locations, and each one compared up without any issues.

Eventually this would have gone into a library for codeigniter, but alas, I can’t even get the loader to work, and loathe to use a different loader, given that code igniter doesn’t have a loader in v3.


Many Thanks,

Christopher East MBCS

Serves as;
Honorary Secretary
Internet Specialist Group
https://u4755625.ct.sendgrid.net/wf/click?upn=dRHYQCJokGWz7dUM0PuPveTdqjhkbtlmYeume7kRLeg-3D_s5UH8bhnBaopYjthcNSRceYlubo729RuvV42OCG7EJtEjCbraBOMscWOhqAY0a400mjn7kidg8XhUpQQ7IZnEGd-2BCEHyqC8qd-2FjfqE7LOypUhnr7jSOmasCPkO6NOua8fPUX9eyYc8gk5YIlWw5a-2FIx00KYUB5avqDcT3SkRnZFQ7pLqowwjzoj-2BrBISpk3gkxAx2kA2Z-2FA3UfNabc3sZPSLSKNnEr1fE0-2FtKgg7wx0C6x48N7Oo-2BzJB2pcVjeiWF16L3NRD7ctVpgsUGXJebY94eAfHzoUgazNwufSW5P69ycKXfSIQ6d-2B5o8Knvo2TdcfQ594DsrS69fsSTMQCIg-3D-3D

Secretary & Recording and Broadcasting Committee Member
BCSWomen Specialist Group
https://u4755625.ct.sendgrid.net/wf/click?upn=swK2tUL-2BSRqqQozs-2FIUZEQEansIQRSUOwm4NBdMvv3k-3D_s5UH8bhnBaopYjthcNSRceYlubo729RuvV42OCG7EJtEjCbraBOMscWOhqAY0a400mjn7kidg8XhUpQQ7IZnEGd-2BCEHyqC8qd-2FjfqE7LOypUhnr7jSOmasCPkO6NOua8fPUX9eyYc8gk5YIlWw5a-2FIx00KYUB5avqDcT3SkRnZFQ7pLqowwjzoj-2BrBISpk3gHwIxjdSkyOGeCRUTryfNC6yOuQiFB-2B3TI7SrlgPsryBefzcfxxEJyA3ArNGUitCOJ77BsoCU3MBzGLwEOSHud0yolJlS6pgPrHUX3w6j-2F3U5gefgDVbtv7g2-2Bn3So8pdQHLMbYg9Y1HrAGjqq0Vt4A-3D-3D


BCS – The Chartered Institute for IT
Based in Sutton, London, UK
Telephone: +44 (0) 7490 079276

The content of this email is the opinion of the sender and does not represent the official view of the Internet Specialist Group within the Chartered Institute for IT, or the Chartered Institute for IT itself. If you could like the official position of the Chartered Institute for IT on any particular topic or subject, then please contact the Chartered Institute for IT online via https://u4755625.ct.sendgrid.net/wf/click?upn=fvYpIyK-2BnzuvtNboPPPSEXvkhU-2Fct-2BFKaueuNTD9odD-2FXcAk4A7UaUZJw8ArRTS1_s5UH8bhnBaopYjthcNSRceYlubo729RuvV42OCG7EJtEjCbraBOMscWOhqAY0a400mjn7kidg8XhUpQQ7IZnEGd-2BCEHyqC8qd-2FjfqE7LOypUhnr7jSOmasCPkO6NOua8fPUX9eyYc8gk5YIlWw5a-2FIx00KYUB5avqDcT3SkRnZFQ7pLqowwjzoj-2BrBISpk3gVT4s5dG2vRLAZOMrJigabszIaAcKhjAc1WkbbCW0ZpCGHYwz2ZBVwDu3a3NY0xF-2FJaEVx5REuG5aXW04jbKC8xezb8rGb0oBbpdaws4u5z6WxVxoMfikze51VvUopDq-2BCwNddxHv1QWd09Mi-2FCh3Nw-3D-3D<https://u4755625.ct.sendgrid.net/wf/click?upn=ChYTglDbII7uRJcv5aHLEdBO9gPpF0YpZ1BLfCbjpw1ATL-2FcsdQb-2BgHthDTH1x5GEea5Ci3Ss27pyqrOYY4JRlEzbcYS84r64HgVReKd2zZvTEPSDSC3-2Fwo1-2B1F8YkbXHotbni6XEhWbSumVG05QbR8j91nmuvMwBBbi75krCj014YQtdguQaAmVavP2sQlrF3bsaIChHgLOElw9rasDNgdLEHJmXm4VJaDVdbKoYKYWJcZgg4eSQMFnseM8Hjo83zVhfHmKuuTa-2Fv5Wc9cMIU-2BHBGIXN4xJwIARCuQ5t8TC8tLPSMCFMzCOp5205ujnOyMuxmFQs3liGdp-2Bti-2Fpmz66AyGZX5KaA2kx8mSMTHuNrsGbipTKzDep2z8INiPK4eOvC-2BxdktZ8j7tMKPsmQc96B-2FXs-2BQXFd4odndi-2FRv0Ju9pj6Jobst8jqIhkFxyMAFsFjYmJb8aG9gCm8EY9AqCyDVwHziO-2Fq4H6lP3o4iiUy7T5EUpL8r8J24wYRX5J_s5UH8bhnBaopYjthcNSRceYlubo729RuvV42OCG7EJtEjCbraBOMscWOhqAY0a400mjn7kidg8XhUpQQ7IZnEGd-2BCEHyqC8qd-2FjfqE7LOypUhnr7jSOmasCPkO6NOua8fPUX9eyYc8gk5YIlWw5a-2FIx00KYUB5avqDcT3SkRnZFQ7pLqowwjzoj-2BrBISpk3gt9yTaj04RFC3f7LEX2dPpZFkOTnyN2m6L9XfTrCTyJabRtCb-2BIEdHZeJq6MJkRtrLeUfzDymi41-2FZO3QQKZLZjyn66-2FAJdIuObsra99nlK5fRFQqrbdv24dAc168aiO-2BAAQVaDY2TY2zc4IQL800UQ-3D-3D> or by calling them on +44 (0) 1793 417424.

This email is confidential and intended for the recipient only. If you receive this email in error, please respond to this email informing them of the error and remove all copies of this email from your system.

In line with standard anti-virus and anti-malware procedures, you should check any and all emails received for malware, and other things which may be harmful to your systems. No liability will be accepted for any damages caused as a result of this email. If you do not have any reputable anti-virus or anti-malware software packages on your computer, please consider installing one as soon as you are able. Many of the packages available are free of charge, so there really is no excuse. Need help choosing, installing, or upgrading your anti-virus, anti-malware, or other security software? Why not ask me, I'm always willing to help!

Please consider the environment before printing this email. Do you really need to print this email? On average a UK business wastes as much as 5KG of paper every week for each person employed. (Credit: Statistics.gov.uk<https://u4755625.ct.sendgrid.net/wf/click?upn=ChYTglDbII7uRJcv5aHLEdBO9gPpF0YpZ1BLfCbjpw1ATL-2FcsdQb-2BgHthDTH1x5Giv-2B-2BEs9b6aV3wL0Lr2g3BTrnxW0m83eLetdqBh9fdx1Q-2BlNr7cBmbelrRk2GzUvcnsDh3sXYMkfIGa6wKi48arwClQVUf15DcMc7-2B6vny1C4X2erWJ-2BkhR-2F4Ukl8iw0Fegfdqcta8CHn6wi7lVgHfLYPRa0wflf-2FMSPXd-2FE-2FCPUt8QzMNTdkncpiITJdvRmQstmNl2j6CXKP5XbPQ1evTS3Wfi-2BKkdjqrvCjk5-2FO119-2Bm7HUnHQ0I22JQNcwJF8Z-2FPnMp0ECsJUbLcsXvc4B5eRlWV-2FDNHSLaMFAnlawV8RSqKCXhu7ZV-2FlRkLmtrm5t1gjCoeRmWsqzvlTUDJv94ZMXsAu3lpCDGZ6N0Yu1-2FdnIRLLXMts23444zmBjjCf8w-2BPV0bRR0pLusE3AXi3THp3j-2B7eJrGRYepWaYtMbjXV8N-2Bnlj03sO6IMfXAvsDVE3cLGoXDtfbQyPY2UrcZXZQ-3D-3D_s5UH8bhnBaopYjthcNSRceYlubo729RuvV42OCG7EJtEjCbraBOMscWOhqAY0a400mjn7kidg8XhUpQQ7IZnEGd-2BCEHyqC8qd-2FjfqE7LOypUhnr7jSOmasCPkO6NOua8fPUX9eyYc8gk5YIlWw5a-2FIx00KYUB5avqDcT3SkRnZFQ7pLqowwjzoj-2BrBISpk3goyh9XbTLEWWYLk5KmZ-2BpMBhaM4P7HkFG1zYgMtTThSw7ebPMO59qSDXNxcTUHp-2B0eeS6-2FvTIBKbQ6VC4LM5c3IzSmJuXW07Bb215vjxR558bxUeLcRjkydz47mw44G1fVZ-2BW5gHNpNGVzFvCKezpDw-3D-3D> Business Waste)

**Comment by willpower232** [comment]
I have been able to replicate this and the answer is that the path to `Loader::register()` must apparently be from `loader.php`, not where the script is being called from.

Ergo, it should be `../lib`.

An enhancement would be to update `loader.php` to remove the reliance on `$parentPath`.

**Comment by ukitconsultant** [comment]
Ah, okay. I did think that, but didn’t try it, basically time got away from me.

I’ll make the changes now and give it a go!

Many Thanks,

Christopher East MBCS

Serves as;
Honorary Secretary
Internet Specialist Group
https://u4755625.ct.sendgrid.net/wf/click?upn=dRHYQCJokGWz7dUM0PuPveTdqjhkbtlmYeume7kRLeg-3D_s5UH8bhnBaopYjthcNSRcRcGs-2F-2BTzKdQJ-2BC-2FFSgDLQ0Kneqfg6ZwyGnxo7JOwgFXXB-2BLTOcWx72v0IjnG0bd3gHiWbF943y0ftuqzqPRTFB0X9L8qyfts3FxUh5-2FnEI1UWky8Qq-2BQF-2F2sy4kXvoawCKQYXP2kmHQvuOwt-2Fey2Vd9Cxkvt0AVihkOmAclXuFHii6NLz0aRmLEwyU89QfCnx-2FmlLKYeRyyzxqpZNBr-2BtL1zu6LZmLDM4w6AhfkM6X7WDpvWfOzQVlFxQyjRlcbFpUDWEBCO1stBFCovl6tHD6tAjPKnZbABt0DesJ-2F3-2Be-2BTzS1xLDFKD9SHMgIYE8eYg-3D-3D

Secretary & Recording and Broadcasting Committee Member
BCSWomen Specialist Group
https://u4755625.ct.sendgrid.net/wf/click?upn=swK2tUL-2BSRqqQozs-2FIUZEQEansIQRSUOwm4NBdMvv3k-3D_s5UH8bhnBaopYjthcNSRcRcGs-2F-2BTzKdQJ-2BC-2FFSgDLQ0Kneqfg6ZwyGnxo7JOwgFXXB-2BLTOcWx72v0IjnG0bd3gHiWbF943y0ftuqzqPRTFB0X9L8qyfts3FxUh5-2FnEI1UWky8Qq-2BQF-2F2sy4kXvoawCKQYXP2kmHQvuOwt-2Fey2Vd9Cxkvt0AVihkOmAclXuFHGtD2E8pX8VtD6H92cIvt2FsOD-2Fj7UCTUZ18MZvlfJhzzS05B01m36lAK2kVut4gYkT1-2FI2I0BlGjo5OSO64z-2FdQ4LSRkAFwNSWU1rr6Ah0ZzPXa-2FzRlXGv0YDcf7F7KQEDg-2FwK9GQfT-2FsiFyNJiVXg-3D-3D


BCS – The Chartered Institute for IT
Based in Sutton, London, UK
Telephone: +44 (0) 7490 079276

The content of this email is the opinion of the sender and does not represent the official view of the Internet Specialist Group within the Chartered Institute for IT, or the Chartered Institute for IT itself. If you could like the official position of the Chartered Institute for IT on any particular topic or subject, then please contact the Chartered Institute for IT online via https://u4755625.ct.sendgrid.net/wf/click?upn=fvYpIyK-2BnzuvtNboPPPSEXvkhU-2Fct-2BFKaueuNTD9odD-2FXcAk4A7UaUZJw8ArRTS1_s5UH8bhnBaopYjthcNSRcRcGs-2F-2BTzKdQJ-2BC-2FFSgDLQ0Kneqfg6ZwyGnxo7JOwgFXXB-2BLTOcWx72v0IjnG0bd3gHiWbF943y0ftuqzqPRTFB0X9L8qyfts3FxUh5-2FnEI1UWky8Qq-2BQF-2F2sy4kXvoawCKQYXP2kmHQvuOwt-2Fey2Vd9Cxkvt0AVihkOmAclXuFH1ucP29g1H0UaFBJeFrSu4uzidjYY9n2l29odSgvnDbTRYERVapC1ZiQJiWzkG05hx3FuQ1vQEeIkyjj1zrvOtw17jhiQjCljJhJ7VUlSk7O9WoCjhvx6s-2Ba0aRPh0OTQpB5JtHASxIi-2Bq8izLGNJPQ-3D-3D<https://u4755625.ct.sendgrid.net/wf/click?upn=ChYTglDbII7uRJcv5aHLEdBO9gPpF0YpZ1BLfCbjpw1ATL-2FcsdQb-2BgHthDTH1x5GEea5Ci3Ss27pyqrOYY4JRlEzbcYS84r64HgVReKd2zZvTEPSDSC3-2Fwo1-2B1F8YkbXHotbni6XEhWbSumVG05QbR8j91nmuvMwBBbi75krCj014YQtdguQaAmVavP2sQlrF3bsaIChHgLOElw9rasDNgdLEHJmXm4VJaDVdbKoYKYWJcZgg4eSQMFnseM8Hjo83zVhfHmKuuTa-2Fv5Wc9cMIU-2BHBGIXN4xJwIARCuQ5t8TC8tLPSMCFMzCOp5205ujnOyMuxmFQs3liGdp-2Bti-2Fpmz66AyGZX5KaA2kx8mSMTHuNrsGbipTKzDep2z8INiPK4eOvC-2BxdktZ8j7tMKPsmQc96B-2FXs-2BQXFd4odndi-2FRv0Ju9pj6Jobst8jqIhkFxyMAFsFjYmJb8aG9gCm8EY9AqCyDVwHziO-2Fq4H6lP3o4iiUy7T5EUpL8r8J24wYRX5J_s5UH8bhnBaopYjthcNSRcRcGs-2F-2BTzKdQJ-2BC-2FFSgDLQ0Kneqfg6ZwyGnxo7JOwgFXXB-2BLTOcWx72v0IjnG0bd3gHiWbF943y0ftuqzqPRTFB0X9L8qyfts3FxUh5-2FnEI1UWky8Qq-2BQF-2F2sy4kXvoawCKQYXP2kmHQvuOwt-2Fey2Vd9Cxkvt0AVihkOmAclXuFHif06wkMQUjJ-2Bn2A0lnsYF-2FX08NYjMPZpYOjdKGke2Tbh6E500-2Fkx42UiTHrZUHT8Ydq5LfNFOud-2BQWYVjxA8W9D4Gpy96s94O5YocStqgz0ZZ8Nfmo9489fhqHuy2fx5ZbuC9A7eKhbC0eR9nzHUDA-3D-3D> or by calling them on +44 (0) 1793 417424.

This email is confidential and intended for the recipient only. If you receive this email in error, please respond to this email informing them of the error and remove all copies of this email from your system.

In line with standard anti-virus and anti-malware procedures, you should check any and all emails received for malware, and other things which may be harmful to your systems. No liability will be accepted for any damages caused as a result of this email. If you do not have any reputable anti-virus or anti-malware software packages on your computer, please consider installing one as soon as you are able. Many of the packages available are free of charge, so there really is no excuse. Need help choosing, installing, or upgrading your anti-virus, anti-malware, or other security software? Why not ask me, I'm always willing to help!

Please consider the environment before printing this email. Do you really need to print this email? On average a UK business wastes as much as 5KG of paper every week for each person employed. (Credit: Statistics.gov.uk<https://u4755625.ct.sendgrid.net/wf/click?upn=ChYTglDbII7uRJcv5aHLEdBO9gPpF0YpZ1BLfCbjpw1ATL-2FcsdQb-2BgHthDTH1x5Giv-2B-2BEs9b6aV3wL0Lr2g3BTrnxW0m83eLetdqBh9fdx1Q-2BlNr7cBmbelrRk2GzUvcnsDh3sXYMkfIGa6wKi48arwClQVUf15DcMc7-2B6vny1C4X2erWJ-2BkhR-2F4Ukl8iw0Fegfdqcta8CHn6wi7lVgHfLYPRa0wflf-2FMSPXd-2FE-2FCPUt8QzMNTdkncpiITJdvRmQstmNl2j6CXKP5XbPQ1evTS3Wfi-2BKkdjqrvCjk5-2FO119-2Bm7HUnHQ0I22JQNcwJF8Z-2FPnMp0ECsJUbLcsXvc4B5eRlWV-2FDNHSLaMFAnlawV8RSqKCXhu7ZV-2FlRkLmtrm5t1gjCoeRmWsqzvlTUDJv94ZMXsAu3lpCDGZ6N0Yu1-2FdnIRLLXMts23444zmBjjCf8w-2BPV0bRR0pLusE3AXi3THp3j-2B7eJrGRYepWaYtMbjXV8N-2Bnlj03sO6IMfXAvsDVE3cLGoXDtfbQyPY2UrcZXZQ-3D-3D_s5UH8bhnBaopYjthcNSRcRcGs-2F-2BTzKdQJ-2BC-2FFSgDLQ0Kneqfg6ZwyGnxo7JOwgFXXB-2BLTOcWx72v0IjnG0bd3gHiWbF943y0ftuqzqPRTFB0X9L8qyfts3FxUh5-2FnEI1UWky8Qq-2BQF-2F2sy4kXvoawCKQYXP2kmHQvuOwt-2Fey2Vd9Cxkvt0AVihkOmAclXuFHH-2FHRX9bUqatnOCq9NV8YxxQwiorTmKr6jcGJ-2Fn1SOcE3IaNWvm19LOEFs28lxzI4Pgadwlra2zZ-2Bei4LPSuawcYWNRhYIRfvPDKbj1q1247DRf-2FeYHMosOsifnGAqrJlHDbalFxibXFZ43IjA1VkMw-3D-3D> Business Waste)

**Comment by RobThree** [comment]
@ukitconsultant Could you, please, for the love of God get rid of [this stupendously big email footer of yours](https://user-images.githubusercontent.com/607888/34463079-21ccca68-ee52-11e7-8781-754df46bd623.png) or at least have the courtesy to delete it before replying? This is ridiculous. I have removed them from all your messages, FYI.

**Comment by RobThree** [comment]
Assuming PEBKAC 😜
