### ISSUE TITLE
How to add custom image for the app?

### ISSUE THREAD

**Issue by edgren** [RobThree/TwoFactorAuth#28]
Hi!

It appears that you cannot set a image for the icon in Google Authentication or similar applications that supports Google Authentication. When you have scanned the QR code, the icon for the service is a standard Android icon.

Is there any way to set this icon to something else?

**Comment by RobThree** [comment]
There's nothing about that in the standards AFAIK. Haven't seen it either. You have a screenshot?

**Comment by edgren** [comment]
Ok. Yes, I have. You can see the Facebook icon above the standard Android icon.

![p1300610](https://user-images.githubusercontent.com/419957/37876441-ac414908-304c-11e8-9e4d-aadadf00f92b.jpg)

**Comment by RobThree** [comment]
LOL; I know what an icon is, that's not why I asked for a screenshot. I was curious about the QR code and/or the app you're using. 

Again, to my knowledge, there's no way to specify an icon in the QR code so I'm pretty sure the app detects which site is sending you the One Time Password and then retrieves the site's favicon or picks an icon from a hardcoded list of icons or something.

Either way; this is nothing the TwoFactorAuth should be concerned about; it'll be up to you to implement this.

**Comment by willpower232** [comment]
Which authenticator app are you using? I'm using the Google Authenticator app and it doesn't have those.

**Comment by edgren** [comment]
@RobThree: Haha! Easy happen :P

Ah! Ok. I think it makes for sense to let the app fetch the favicon for the website. But if you find anything that let you add an icon for your website, please add it to your lovely TwoFactorAuth :)


@willpower232: I'm using [Authenticator Plus](https://www.authenticatorplus.com/). Unlike Google Authenticator, Authenticator Plus offers synchronizing to the cloud, a dark theme, and a lot of more settings, which to me is much better than Google's app :)

**Comment by RobThree** [comment]
> Ah! Ok. I think it makes for sense to let the app fetch the favicon for the website. 

I'm not sure if that's what it does; unfortunately the project seems to be closed source so I can't take a look at what it does / how it does it.

> But if you find anything that let you add an icon for your website, please add it to your lovely TwoFactorAuth :)

This library has exactly 0 UI elements; it only contains functions for generating secrets, sharing them with QR codes and verifying HOTP. Anything UI related is up to the user of this library; icons are of no concern for this library, ever, so it won't be put it. Sorry.
