### ISSUE TITLE
Generate backup codes

### ISSUE THREAD

**Issue by pH-7** [RobThree/TwoFactorAuth#3]
Hi Rob! Nice work :smiley: 

Wondering how I can generate backup codes (that are never expired).

I use `->getCode($secret);` but doesn't after 30sec, 1min it doesn't work or never worked. Any idea why and how to fix it?

 Thx!

**Comment by RobThree** [comment]
You should just create `X`-number of random strings (or numbers) as backup code and store (**salted hashes** of) them somewhere safe. If the entered code doesn't match you check the input against the `X` hashes you stored.
