### ISSUE TITLE
How to use timeslice argument

### ISSUE THREAD

**Issue by willpower232** [RobThree/TwoFactorAuth#30]
As per your recent 1.6.2 release,

> The verifyCode(...) method now has a new argument that returns the timeslice that matched the code so you can save the timeslice and prevent replay-attacks.

I'm not completely sure how to use the timeslice argument, would you **always** save it against the user and **always** pass it in from your records when verifying the user?

Thanks for your work

**Comment by RobThree** [comment]
You can save the timeslice (on successful login) for a user to prevent (or at least detect)  a [replay-attack](https://www.slideshare.net/zerocool51/google-authenticator-possible-attacks-and-prevention) (see slide 21). You don't _need_ to use it (it's optional) but it _does_ strengthen your 2FA implementation.

So: A user logs in, TOTP code is verified to be correct, store timeslice in your database with the user. Next time a user logs in ensure the timeslice > previous timeslice.

**Comment by willpower232** [comment]
ah I see, so don't send the previous timeslice to `verifyCode`, just check it after a valid result. Something like this?

```php
if ($tfa->verifyCode($user->secret, $inputcode, 1, null, $timeslice) === true && $timeslice > $user->lastvalidtimeslice) {

    // valid login, create session bits here

    $user->lastvalidtimeslice = $timeslice;
    $user->save();
}
```

**Comment by RobThree** [comment]
Exactly 👍

**Comment by RobThree** [comment]
I [updated the documentation](https://github.com/RobThree/TwoFactorAuth/commit/e74f7a4bf6621211de615c7ad19c22d1c6e64827#diff-04c6e90faac2675aa89e2176d2eec7d8R96) to explain what it's for.
