### ISSUE TITLE
verifyCode() returning TRUE where on localhost but not where live

### ISSUE THREAD

**Issue by hiddeneyes02** [RobThree/TwoFactorAuth#31]
Thanks for this scripts, but as in the title. Things are working fine when on localhost, but when using it live on server, verifyCode() alwats returns false.

I used ensureCorrectTime(), and it is not throwing any exception
I also set $discrepancy to 10, but nothing

Here is my code:

```
$tfa = new TwoFactorAuth('Control');
$code = filter_input(INPUT_POST, 'code');

var_dump($tfa->verifyCode($secret, $code, 3));
```

Could it be a timezone issue? How can I debug this?

**Comment by willpower232** [comment]
Is the secret exactly the same local and live?

Are you able to tell if the server is running NTP?

Can you access the terminal of the server (i.e. SSH) and see what the time is on the server?

**Comment by hiddeneyes02** [comment]
It was the one, really sorry for the inconvenience

**Comment by RobThree** [comment]
Glad you solved it yourself 😉 👍
