### ISSUE TITLE
verify code always return false

### ISSUE THREAD

**Issue by ongyen8888** [RobThree/TwoFactorAuth#32]
Hi, I'm creating TwoFactorAuth instance in two different function. One function will generate the code and the other function will verify the code but I found out that it always return false when verifying the code. If I want to send out the code in the first function and use the other function for verification, are there any solution for this?

**Comment by RobThree** [comment]
You closed this? So I can assume you found a/your mistake? Care to share for others that may encounter the same problem?

**Comment by ongyen8888** [comment]
I found my mistake already, thanks.

**Comment by RobThree** [comment]
Again: Care to share for others that may encounter the same problem? 😉

**Comment by ongyen8888** [comment]
@RobThree one of my variable name is wrong only if this is what you want to know.
