### ISSUE TITLE
VerifyCode ERROR

### ISSUE THREAD

**Issue by qcmarcel** [RobThree/TwoFactorAuth#35]
![image](https://user-images.githubusercontent.com/13855572/55365602-ba670d00-54aa-11e9-8cd3-2399c9f23d5c.png)

**Comment by qcmarcel** [comment]
Please push button entering this secret: NQI4GMOPRQMTT54RH6SDHC

**Comment by RobThree** [comment]
Stop opening issues. Provide an [MCVE](https://stackoverflow.com/help/mcve). That is the **only** way I will help you. I won't visit your site (again), I won't look at your screenshots trying to figure out what is going on and I won't go through all sorts of instructions to try to help you. **You** need to provide an MCVE; that is the only way I will help you.
