### ISSUE TITLE
Support for different authenticator versions?

### ISSUE THREAD

**Issue by judodan** [RobThree/TwoFactorAuth#36]
I like this library. I have implemented TFA in my application and in all my tests, it seemed to work just fine.

I was testing with a couple of different iPhones using the Google Authenticator app, very straightforward.

However, upon deploying, the first user was using an older android phone. She installed Authenticator and took the picture of the QR. It 'seemed' to work, but Authenticator was showing a 6 digit code with a 30 seconds timeout (I have configured for an 8 digit code with a 1 minute timeout). Of course, the code does not work.

Has anybody seen anything similar? Are there different versions of Google Authenticator (there didn't seem to be when we installed it) I should be aware of?

Suggestions appreciated, we're 95% there!

Thanks for all the work on this!

**Comment by lenada** [comment]
Has been a while since I last worked with this... so this is just a quick blind guess from my side:

Could it bee that you are not "configuring" through the '__construct(...)' of the `TwoFactorAuth` class ? As the settings contained in your QR code seem to be the defaults (see constructor).
Also try calling `getQRText()` and check that it contains the settings you are expecting.

**Comment by judodan** [comment]
If the QR code was, in fact, wrong, wouldn't it fail with the iPhone as well?

However, you've given me a good idea, I can try the same code with both the android and iPhone and see if there is a difference. Will check out the QRText as well.

Thanks.

**Comment by RobThree** [comment]
I have tested it, back in the day, on iOS with the Google Authenticator and it supported (back then) some "non common" combinations like 8 digits with 10 second intervals or something like that. However, I would recommend you stick with the 'common' 6 digits, 30 seconds intervals anyway. There's some authenticator apps that don't support other configurations correctly. Anything other than 6 digits, 30 seconds, SHA1 (e.g. 'defaults') _can_ be problematic.

**Comment by judodan** [comment]
I will follow up with the user. Unfortunately, I am not on site anymore. I could go back to defaults, but would that mean anybody else already set up for TFA will have to reconfigure?

Will let you know what I find.

Thanks.

**Comment by RobThree** [comment]
>  but would that mean anybody else already set up for TFA will have to reconfigure?

It would. However, it's up to you to decide if you want that, or try getting 8 digits, 60 second intervals to work. Either is an option ofcourse.

**Comment by judodan** [comment]
Sadly, I couldn't find anything (other than Google Authenticator on my iPhone) that would work with 8 digits and 60 second intervals, so I just went back to the defaults. Disappointing.

**Comment by RobThree** [comment]
Out of curiosity, why would you want 60 second intervals / 8 digits? Besides the fact that it _should_ work but isn't supported by many authenticators; what makes you want this particular configuration?

I assume you want the 60 second interval for users to allow for more time to enter the code; however, that can easily be achieved using a larger `$discrepancy ` when calling `verifyCode()`. The extra digits would add slightly better security but it's probably negligible anyway.

**Comment by judodan** [comment]
Pretty much what you've guessed. In the test run, a number of people had trouble getting the code in within 30 seconds. It's not insurmountable. More security for 8 digits. Don't know why, but 8 seemed like a 'more secure' number, but like you said, probably negligible

**Comment by RobThree** [comment]
👍 Thanks for the feedback! I'll close this issue then.
