### ISSUE TITLE
Watermark in QR code when using the default QR Code provider

### ISSUE THREAD

**Issue by Stereoide** [RobThree/TwoFactorAuth#37]
When using the default QR Code Provider the generated QR code contains a watermark which - at least for me - breaks scanning the code with the Authy app.

image-charts.com recently changed the behaviour regarding the creation of charts/QR codes. As per their website of today:
"QR Codes finaly came out of beta! Free users will have the watermark [..]"

Switching to "QRServerProvider" fixes the problem at hand.

**Comment by RobThree** [comment]
Dangit. So much for image-charts.com. I've had it with online services anyway. I'm considering switching to a composer package so QR generation can be done locally. Any good suggestions?

**Comment by willpower232** [comment]
https://github.com/Bacon/BaconQrCode is pretty flexible, been using it with this library for a while.

**Comment by RobThree** [comment]
As a 'quick fix' I switched to `QRServerProvider` as default (1.6.7). I am looking into / working on including a 'local' QR code generator.

**Comment by tobwen** [comment]
What about doing it in the frontend? https://davidshimjs.github.io/qrcodejs/

**Comment by RobThree** [comment]
That wouldn't fit the current interface where the "image" (base64 encoded data) is returned. It could be made to work but would require some (breaking) changes.
