### ISSUE TITLE
socket_recv(): unable to read from socket

### ISSUE THREAD

**Issue by RoyvEmpel** [RobThree/TwoFactorAuth#42]
Hello,

I was testing with the TwoFactorAuth library and got this warning while running the ensureCorrectTime function which is giving me some problems. I'm running this from a localhost laragon server with php 7.1.23 and i have tried running the php.net socket example to test if my sockets where working correctly and there doesn't seem to be any problems when i try that. 

Is there something i am missing or doing wrong?

Greetings,
Robgeus

```
require_once 'twofaloader.php';
Twofaloader::register('/2faDependencies/TwofactorAuth','RobThree\\Auth');

use \RobThree\Auth\TwoFactorAuth;

class Twofa 
{

  public $twofa = null;

  public function __construct()
  {
    $this->tfa = new TwoFactorAuth('MyProject');

    try {
      $this->tfa->ensureCorrectTime();
      echo 'Your hosts time seems to be correct / within margin';
    } catch (RobThree\Auth\TwoFactorAuthException $ex) {
      echo '<b>Warning:</b> Your hosts time seems to be off: ' . $ex->getMessage();
    }
  }


}
```

![afbeelding](https://user-images.githubusercontent.com/36758721/72438680-a1171f00-37a5-11ea-84b1-820d8a38841a.png)

**Comment by RobThree** [comment]
You could try another time provider (like the `HttpTimeProvider`) or, alternatively, try another NTP server; I recently had some trouble because the ntp pool was unreachable. Instead of [the default](https://github.com/RobThree/TwoFactorAuth/blob/c6f1f4748170c8692cff4d086408f05782bb5d7c/lib/Providers/Time/NTPTimeProvider.php#L14) `time.google.com` try `pool.ntp.org` or some NTP server at your provider.

**Comment by robgeus** [comment]
So i tried the `pool.ntp.org` as NTP server with it working only once and after that the error came back. But when trying the HttpTimeProvider I am getting the error: `Fatal error: Uncaught Error: Class 'TimeException' not found`. Also i was trying the MSG_PEEK flag for socket_recv and then i get the same error. ^^^^

**Comment by RobThree** [comment]
The `TimeException` error sounds like TimeException.php not being included/required. Can you check that?
The rest sounds like a connectivity issue somewhere? I'm not sure? If possible, could you try debugging the issue and let me know what you find?

**Comment by robgeus** [comment]
so the TimeException error was because i forgot to remove a echo from the code. After removing it its now working :). I also got the NTPTimeProvider working with changing the socket_recv MSG_WAITALL to MSG_PEEK. The error returns when i change it back to msg_waitall
