### ISSUE TITLE
Auth code is always true when the period time is over

### ISSUE THREAD

**Issue by khuyennguyen7007** [RobThree/TwoFactorAuth#43]
Hi @RobThree ,
When I'm using your lib, I founded that if the period time is over, The auth code before still valid (attached video).
[https://streamable.com/qdqvy](https://streamable.com/qdqvy)
```
<?php
require_once __DIR__ . '/vendor/autoload.php';
$tfa = new RobThree\Auth\TwoFactorAuth('My Company');
$secret = 'NEJT2GA4E2A7M534';
echo $secret;
?>
<p><img src="<?php echo $tfa->getQRCodeImageAsDataUri('Khuyen Nguyen', $secret); ?>"></p>
<?php
$code = '326055'; //613491
$isValid = $tfa->verifyCode($secret, $code);
echo '<br>';
if ($isValid) {
    echo 'Valid';
} else {
    echo 'Invalid';
}
```
Please correct me.

**Comment by RobThree** [comment]
Have you read the explanation in [Step 2](https://github.com/RobThree/TwoFactorAuth#step-2-verify-secret-shared-key) about the `$discrepancy`? By default most TOTP implementations allow one, two or sometimes even 3 timeslices of time difference to account for TOTP-clients not having the correct (exact) time.

If you set the `$discrepancy` to 0 the code should ONLY be valid for that timeslice.

**Comment by khuyennguyen7007** [comment]
Oh, that is my mistake. After change the `$discrepancy` to 0. It's working properly. Thank you very much.

**Comment by RobThree** [comment]
Please make sure you know what you're doing. A `$discrepancy` of zero is not very usual and could cause your users to experience problems if their device is more than 30 seconds (or whatever interval you choose) off. It's *usually* not a problem to allow for a small `$discrepancy` of up to, say, 2 minutes in either direction of current time.

**Comment by khuyennguyen7007** [comment]
Yeah! Thanks for your advice. I will consider it. :v:
