### ISSUE TITLE
VerifyCode returns false / ensureCorrectTime issue

### ISSUE THREAD

**Issue by luggesexe** [RobThree/TwoFactorAuth#49]
Hello,
I was trying to implement your library into my project. 
The QR Code as well as the Code are being generated properly but I can't verify the Code.

After looking at the code I thought about, that the Time could be an issue. After trying the code 
`try {
        $tfa->ensureCorrectTime();
        echo 'Your hosts time seems to be correct / within margin';
    } catch (RobThree\Auth\TwoFactorAuthException $ex) {
        echo '<b>Warning:</b> Your hosts time seems to be off: ' . $ex->getMessage();
    }`

I get the following error
Uncaught Exception: Connection refused
extern/lib/Providers/Time/NTPTimeProvider.php Zeile 40
Backtrace
#0 extern/lib/TwoFactorAuth.php(157): RobThree\Auth\Providers\Time\NTPTimeProvider->getTime()
#1 extern/2fa.php(39): RobThree\Auth\TwoFactorAuth->ensureCorrectTime()
#2 {main}

NTPTimeProvider.php
` /* Receive response and close socket */
            if (socket_recv($sock, $recv, 48, MSG_WAITALL) === false)
                throw new \Exception(socket_strerror(socket_last_error($sock)));
            socket_close($sock);`

So it's probably an Time issue I can't verify.

Also do I set the discrepancy in the `TwoFactorAuth.php`
like this `public function verifyCode($secret, $code, $discrepancy = 4, $time = null, &$timeslice = 0)`

or in my file with
`$Ergebnis= $tfa->verifyCode($secret, $_POST['verification'], $discrepancy);`

Many regards
Lukas

**Comment by RobThree** [comment]
The first issue sounds like the server isn't able to reach `time.google.com`. You can try a ping or something to see if it should be reachable, try a different NTP server or even an different `TimeProvider`.

About your second question: the `TwoFactorAuth` class has no `$discrepancy` constructor argument? It does have a `$period` argument, but those two things are totally different. The `$period` determines how long a code is valid (30 seconds by default) and the `$discrepancy` determines how many periods the client device may be "off" time-wise. So for a `$discrepancy` of 4 the code will be valid 4 + 4 (both ways) * 30 seconds = 4 minutes. Or: your client device may be "off" by 2 minutes in either direction.

I would like to point out that all of this is documented in the README.

**Comment by luggesexe** [comment]
So I deleted the NTPTimeProvider in the `TwoFactorAuth.php` although the Google Server responds to a Ping.
After that I got a response that the host time seems to be correct. 

I still just get false as a response although I'm copying the generated code into my form, so I can't really figure it out why it doesn't work.

**Comment by willpower232** [comment]
are you able to manually verify the time on your computer/server is correct for your timezone? If you're on mac or linux you could compare the output of the `date` command in a terminal with https://time.is. Windows has a sync button somewhere for it.

**Comment by RobThree** [comment]
And if that doesn't help, please show us your code or at least tell us the configuration (period, digits, algorithm) and which authenticator app you're using.

**Comment by luggesexe** [comment]
So apparently the Server time is about 4 minutes off.
I tried to solve it by setting the discrepancy to 10 but still not working.
The code can be found below.

```
require_once 'loader.php';
Loader::register('lib','RobThree\\Auth');

use \RobThree\Auth\TwoFactorAuth;

$tfa = new TwoFactorAuth('Service Portal)');

$secret = $tfa->createSecret(160);


echo '<img src="' . $tfa->getQRCodeImageAsDataUri('SAP', $secret) . '"><br>'.chunk_split($secret, 4, ' ');
$code = $tfa->getCode($secret);
echo $code; // Displaying code for testing reasons


<form action="?verify=1" method="POST">
	<div class="input-form">
		<input type="number" name="verification">
		<button class="regBtn" type="submit">Senden</button>
	</div>
</form>

if (isset($_GET['verify'])) {
            $result = $tfa->verifyCode($secret, $_POST['verification'], $discrepancy);
		    	if ($result) {
				die('<meta http-equiv="refresh" content="0; URL=dashboard">');
		    	} else {
		    		echo "Es ist leider ein Fehler aufgetreten, bitte versuchen Sie es noch einmal.";
		    	}
 }
```

Using Google Authenticator with standard configuration (except $discrepancy = 10)

**Comment by RobThree** [comment]
Google Authenticator won't handle anything but 80 bits / 30 seconds / sha1 (e.g. default configuration). So instead of `$tfa->createSecret(160);` try `$tfa->createSecret();`

**Comment by luggesexe** [comment]
`$_POST['verification']` contains the right information,
Also not working with 80.
`$result = $tfa->verifyCode($secret, $_POST['verification'], $discrepancy);` I do here, but I don't know if this is correct.

**Comment by RobThree** [comment]
Does the demo work for you?

**Comment by luggesexe** [comment]
Yes, it shows OK as a result

**Comment by RobThree** [comment]
Then can't you try and figure out what the difference between the two is and narrow it down?

```php
require_once 'loader.php';
Loader::register('../lib','RobThree\\Auth');

use \RobThree\Auth\TwoFactorAuth;

$tfa = new TwoFactorAuth('MyApp');

$secret = $tfa->createSecret(160); 
$code = $tfa->getCode($secret);
$result = $tfa->verifyCode($secret, $code) === true;
```

This is the relevant code from the demo. There must be some difference in the code you're using. Also try adding `error_reporting(E_ALL); ini_set("display_errors", 1);` as very first line if you don't have it already.

**Comment by luggesexe** [comment]
So Error reporting displayed `Notice Undefined variable: discrepancy`
in Line 113 `$result = $tfa->verifyCode($secret, $_POST['verification'], $discrepancy);`

**Comment by luggesexe** [comment]
So I checked everything and apparently it's an POST Error because when I check using the $code Variable everything it's working perfectly fine. But I checked and the code I'm posting is the same.

**Comment by RobThree** [comment]
I'm sorry but I can't help you with that. The problem is obviously in your code and not in TwoFactorAuth.

Also, judging from the _`Notice Undefined variable: discrepancy in`**`Line 113`**_ the code you've posted here is not the code you're actually using so that makes it hard for us to debug the issue.

For a quick'n'dirty check to see if TwoFactorAuth works correctly you could simply replace `$discrepancy` on the aforementioned line 113 with a constant (like 3 or 4 or ...)

**Comment by luggesexe** [comment]
So yes I got the Error resolved with the `$discrepancy`.
What exactly expects the $code?
I'm entering a string, so this should be fine, if the code works if I take the $code variable because they are the same.

**Comment by RobThree** [comment]
I kindly request you refer to the documentation and/or demo. This question is answered there.

**Comment by luggesexe** [comment]
Okay figured it out, thanks!

**Comment by RobThree** [comment]
@luggesexe: It would be nice if you posted what the issue was so that others can learn from it too.

**Comment by luggesexe** [comment]
I called ?verify=1. That generated a new secret so it was always false. 
Figured it out by creating a new page where I checked the two belonging POST Variables.
