### ISSUE TITLE
CURLOPT_FOLLOWLOCATION and open_basedir

### ISSUE THREAD

**Issue by jportoles** [RobThree/TwoFactorAuth#5]
Hey, great work on the library, we've been testing it and it seems to be pretty robust. We ran into a minor issue and I'd like to propose a change:

Basically, BaseHTTPQRCodeProvider crashes if the `open_basedir` php directive is set, and it doesn't appear that a workaround exists:

http://stackoverflow.com/questions/19539922/php-can-curlopt-followlocation-and-open-basedir-be-used-together

And while "just turn the directive off" can be a solution for some, like the thread there suggests it can be a security liability to get rid of it. So I would vote to remove CURLOPT_FOLLOWLOCATION from the class, unless there's a compelling reason to keep it. Google Charts seems to work fine at least without redirects.

**Comment by RobThree** [comment]
I don't have a problem with removing the `CURLOPT_FOLLOWLOCATION` option. On it.

**Comment by RobThree** [comment]
[Here you go](https://github.com/RobThree/TwoFactorAuth/releases/tag/1.5)!

**Comment by jportoles** [comment]
Hurray, thanks! :) We were already running this change in a hacky way, but it's always nicer to have it in the upstream version.
