### ISSUE TITLE
Home page states that it is an improvement on PHPGangsta/GoogleAuthenticator but not what it entails.

### ISSUE THREAD

**Issue by cmanley** [RobThree/TwoFactorAuth#53]
Please add what the improvement(s) are over PHPGangsta/GoogleAuthenticator.

**Comment by RobThree** [comment]
It's exactly that. It was inspired by PHPGangsta/GoogleAuthenticator but has a much better (api) interface and is much more extensible. If you want to know the exact differences, read the documentation.
