### ISSUE TITLE
Compatibility with Authy using sha256

### ISSUE THREAD

**Issue by deanc** [RobThree/TwoFactorAuth#54]
Hi Rob,

It's mentioned in the docs about adjusting the algorithm from the default sha1. We are in a position we can insist our users use Authy for example, and from a quick google it seems it should support this algorithm, but I can't get codes from Authy verified if I set the algorithm to `sha256`. Only `sha1` works. Can you clarify the situation here? What string exactly should I be supplying there?

BR,
Dean

**Comment by RobThree** [comment]
Which algorithms are supported can be found [here](https://github.com/RobThree/TwoFactorAuth/blob/b5f9eda4994b4f0494452bf7ab18e33c4cd907f7/lib/TwoFactorAuth.php#L22) in the source code and [here](https://github.com/RobThree/TwoFactorAuth#usage) in the README (though I admit, I should've summed up all options there).

When I use the code:

```php
$tfa = new TwoFactorAuth('MyApp', 6, 40, 'sha256');
```
The TOTP codes generated by Google Authenticator, FreeOTP and Lastpass work for me. Authy doesn't, neither does Microsoft's Authenticator.

Though technically SHA256 is 'safer', it's only (very) marginally safer. If it were up to me I'd stick with the most compatible SHA1 algorithm providing the best service to your users being free to use any of the many authenticator apps out there.

**Comment by deanc** [comment]
Thanks Rob. I reached out to Authy to ask about this after writing this issue. It's pretty awful they just ignore the algorithm without an error and return you sha1 codes.

Maybe it would be useful to have a separate markdown document in the Wiki or something detailing which apps support which algos :)

**Comment by RobThree** [comment]
> Maybe it would be useful to have a separate markdown document in the Wiki or something detailing which apps support which algos :)

Meh, that only means more stuff to keep up-to-date. I think a general comment ("make sure you test if you _insist_ on using anything other than SHA1") is better.

> By the way, the wiki redirects me to the repository home right now so I guess it's not enabled?

It's not.

**Comment by deanc** [comment]
I kind of see your point, but if it were on the wiki I presume anyone could keep that info up to date - not you :)?

**Comment by RobThree** [comment]
I kind of see your point too but, in my experience, wiki's don't get updated that often unless it's a -very- popular library. And it might potentially 'cost' some 'customers' if the wiki says X is not supported when it actually is (now). So I'm kind of on the fence on this. Let me think about it for a bit 😉

**Comment by RobThree** [comment]
Also, @deanc, would you happen to have the source stating Authy supports sha256? I would love to see/verify it, maybe set the authors straight (too).

**Comment by deanc** [comment]
It doesn't support it, but it doesn't tell you that it doesn't support it. That's the problem :)

**Comment by willpower232** [comment]
FWIW a github wiki can only be edited by those with push permission on the repo itself so isn't a great collaborative space. A markdown page in the repo code itself is much easier for a community to support.

**Comment by tunnckoCore** [comment]
I can confirm, it DOESN'T support sha256

i'm moving away from it anyway
