### ISSUE TITLE
Support for logos in QR Codes

### ISSUE THREAD

**Issue by igorsantos07** [RobThree/TwoFactorAuth#56]
On quick research, I noticed that Endroid's library allows the embedding of image files in the middle of QR Codes. As that's necessary on my soon-to-be implementation, I'll have to extend TwoFactorAuth's class with that behavior. I want to publish it as a PR as well, if it doesn't feel out of scope for the project (I don't think it should be, anyway).

So, bottom-line: how would that implementation feel better on the project's style? We need two extra values (logo path & size): as more arguments on the constructor, or as an optional, extra method `setLogo()`?

**Comment by RobThree** [comment]
Either option is fine, as long I guess. But I suggest not changing the `EndroidQrCodeProvider` class but rather extending it to an `EndroidQrCodeWithLogoProvider` or whatever better name you can come up with. And if I _had_ to choose I'd pick the constructor option - but that's me.
