### ISSUE TITLE
Composer lacking QrProviders

### ISSUE THREAD

**Issue by VictorVolpe** [RobThree/TwoFactorAuth#58]
Hi, today I faced a long api.qrserver.com outage, so my QR codes were unable to be generated. I'm trying to use the EndroidQrCodeProvider, but the composer installation for robthree/twofactorauth doesn't come with these files (bug?), even with the endroid/qr-code dependency installed. Other files lacking too, like BaconQrCodeProvider.

**Comment by willpower232** [comment]
Currently being discussed in #39 :sweat_smile:

**Comment by willpower232** [comment]
@VictorVolpe this has finally been resolved with [1.8.0](https://github.com/RobThree/TwoFactorAuth/releases/tag/1.8.0), hopefully you're able to make use of the new providers!
