### ISSUE TITLE
Why is method getQRText private?

### ISSUE THREAD

**Issue by JonathanTru** [RobThree/TwoFactorAuth#6]
awesome library, but I don't want to use any of the QRCode Providers, rather I pass the QRCodeText to the Client and have the Javascript Library _qrcode.js_ render the QRCode.

Could you explain to me why the method _getQRText()_ is **private**? Are you open to changing that to **public**?

**Comment by RobThree** [comment]
> Could you explain to me why the method `getQRText()` is private?

I always start out `private` and make stuff `protected` or `public` as needed; (up until now) it wasn't required to make the method `public` hence the `private` access modifier.

> Are you open to changing that to public?

I am. I don't directly see a problem in that. I'll change it and create a new release tonight / soon(-ish).

**Comment by RobThree** [comment]
#7
