### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by willpower232** [RobThree/TwoFactorAuth#69]
It would be good to figure out how we can resolve the [flaky test](https://github.com/RobThree/TwoFactorAuth/blob/30a38627ae1e7c9399dae67e265063cd6ec5276c/tests/TwoFactorAuthTest.php#L56-L67) but hopefully everyone can see it [passes sometimes!](https://github.com/RobThree/TwoFactorAuth/actions/runs/636699230)

I haven't had this flakiness happen locally so its likely to be the runner time being behind the time values returned by the various remote services.

A bypass to this problem could be to use a remote service as the default time provider for that instance of TwoFactorAuth but that would leave the actual default provider untested.

Thoughts @RobThree ?

**Comment by RobThree** [comment]
I've experienced the same flakiness back when we used Travis. I'm not sure what's up with that.

Maybe before any of the tests are run set the clock with NTP? Feels dirty / hacky but I think that would be the best option? Is that even possible?
