### ISSUE TITLE
Install this package outside of project directory

### ISSUE THREAD

**Issue by alve89** [RobThree/TwoFactorAuth#70]
I just noticed a problem with installing this package at the root of my webspace.

From within the root (`/www/htdocs/xxxxx/`) I ran `composer require robthree/twofactorauth` which was installed properly as `/www/htdocs/xxxxx/vendor/robthree/twofactorauth/`.

After copying the files `demo.php` and `loader.php` to my project directory (`/www/htdocs/xxxxx/my/project/path/libs/2fa/`) I changed the line
`Loader::register('../lib','RobThree\\Auth');`
to 
`Loader::register('/www/htdocs/xxxxx/vendor/robthree/twofactorauth/lib','RobThree\\Auth');`
in order to set this absolute path. Calling `demo.php` displays a blank white page.

Even changing
`require_once 'loader.php';`
to
`require_once '/www/htdocs/xxxxx/vendor/robthree/twofactorauth/demo/loader.php';`
didn't change anything.

Installing the package within my project site works fine, I got the QR-Code and the text shown.

What am I missing to use this from a central path (to prevent it from multiple installations and updates)?

**Comment by willpower232** [comment]
I think the demo is quite old and using a custom loader in a project that already has composer might be a problem in itself.

If you want to prevent updates to libraries, you can modify your projects composer.json to mention the specific version you want to use.

If you absolutely have to prevent the duplication of a few kilobytes of code, you can modify your projects composer.json so it makes use of `repositories` and link to the path of the library https://getcomposer.org/doc/05-repositories.md#path

Does this make sense?

**Comment by alve89** [comment]
First of all - thanks for this very quick reply!

> If you absolutely have to prevent the duplication of a few kilobytes of code

It's not about preventing just a few kilobytes, it's more about reducing maintenance effort by simply updating a library in one place (=root) instead of replacing X libraries in X places (=X projects). If I'm wrong with this understanding (that every single instance of you library needs to be updated manually) please tell me - I never used composer before, I just followed the instructions.

> you can modify your projects composer.json so it makes use of `repositories` and link to the path of the library

I tried this in the composer.json within my project:

    {
        "repositories": [
            {
                "type": "path",
                "url": "../../../vendor/robthree/twofactorauth"
            }
        ],
        "require": {
            "robthree/twofactorauth": "*"
        }
    }

After running `composer require robthree/twofactorauth` in my project directory, the folder structures vendor/composer and vendor/robthree/.... are created there - so it's still a duplicate, isn't it?

Do you have more information what I need to do? Especially how to "link" multiple packages (twofactorauth, bacon-qr-code).

**Comment by willpower232** [comment]
Traditionally, each PHP project you develop would have its own composer.json and composer.lock files so that you can install any dependencies you want and lock them at specific versions so that all the code will always be the same when you run `composer install`.

You might find it easier to start from the root `/` directory rather than using `../` in case the path isn't quite right.

`composer install` will always create `vendor` as that is where it lives for your project and you should see in the text output from the command that a link is being created from `vendor` back to where your code is centrally.

**Comment by alve89** [comment]
Alright, thank your for this explanation - then I keep it as it is!
