### ISSUE TITLE
Fatal error: Uncaught Error: Class 'RobThree\Auth\Providers\Rng\CSRNGProvider' not found 

### ISSUE THREAD

**Issue by alve89** [RobThree/TwoFactorAuth#71]
Independend from my question about the composer thing I'm trying to use your library.

I got this error:
`Fatal error: Uncaught Error: Class 'RobThree\Auth\Providers\Rng\CSRNGProvider' not found in /www/htdocs/xxxxx/path/to/my/project/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php:334 Stack trace: #0 /www/htdocs/xxxxx/path/to/my/project/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php(101): RobThree\Auth\TwoFactorAuth->getRngProvider() #1 /www/htdocs/xxxxx/path/to/my/project/demo.php(30): RobThree\Auth\TwoFactorAuth->createSecret() #2 {main} thrown in /www/htdocs/xxxxx/path/to/my/project/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php on line 334`

After commenting out line 334 the error continues for `MCryptRNGProvider`, I then commented this out and repeats for `OpenSSLRNGProvider` and also for `HashRNGProvider`.

The function `random_bytes()` exists and works properly (I'm running PHP 7.4).

That's my code so far:

    require_once 'vendor/robthree/twofactorauth/lib/TwoFactorAuth.php';
    $tfa = new RobThree\Auth\TwoFactorAuth('My Company');
    $secret = $tfa->createSecret();
    varDump($tfa);

**Comment by willpower232** [comment]
You should use `require 'vendor/autoload.php';` to make use of the Composer loader class which should be able to resolve your dependencies.

**Comment by alve89** [comment]
Done. Worked. Close. Thank you!

PS: Perhaps you want to add this hint to the installation guide for composer-inexperienced-users like me...
