### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function RobThree\Auth\Providers\Time\socket_create()

### ISSUE THREAD

**Issue by alve89** [RobThree/TwoFactorAuth#75]
And another one... but here I'm a bit confused about this error as it should be catch actually?

`Fatal error: Uncaught Error: Call to undefined function RobThree\Auth\Providers\Time\socket_create() in /www/htdocs/xxxxxx/mydomain.tld/ssh/libs/googleauthenticator/vendor/robthree/twofactorauth/lib/Providers/Time/NTPTimeProvider.php:46 Stack trace: #0 /www/htdocs/xxxxxx/mydomain.tld/ssh/libs/googleauthenticator/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php(236): RobThree\Auth\Providers\Time\NTPTimeProvider->getTime() #1 /www/htdocs/xxxxxx/mydomain.tld/ssh/libs/googleauthenticator/demo.php(38): RobThree\Auth\TwoFactorAuth->ensureCorrectTime() #2 {main} thrown in /www/htdocs/xxxxxx/mydomain.tld/ssh/libs/googleauthenticator/vendor/robthree/twofactorauth/lib/Providers/Time/NTPTimeProvider.php on line 46`

with this code (from demo.php):

    require_once 'vendor/autoload.php';
    use \RobThree\Auth\TwoFactorAuth;

    $tfa = new TwoFactorAuth('My Company');

        echo '<li>First create a secret and associate it with a user';
        $secret = $tfa->createSecret(160);  // Though the default is an 80 bits secret (for backwards compatibility reasons) we recommend creating 160+ bits secrets (see RFC 4226 - Algorithm Requirements)
        echo '<li>Next create a QR code and let the user scan it:<br><img src="' . $tfa->getQRCodeImageAsDataUri('My label', $secret) . '"><br>...or display the secret to the user for manual entry: ' . chunk_split($secret, 4, ' ');
        $code = $tfa->getCode($secret);
        echo '<li>Next, have the user verify the code; at this time the code displayed by a 2FA-app would be: <span style="color:#00c">' . $code . '</span> (but that changes periodically)';
        echo '<li>When the code checks out, 2FA can be / is enabled; store (encrypted?) secret with user and have the user verify a code each time a new session is started.';
        echo '<li>When aforementioned code (' . $code . ') was entered, the result would be: ' . (($tfa->verifyCode($secret, $code) === true) ? '<span style="color:#0c0">OK</span>' : '<span style="color:#c00">FAIL</span>');
        ?>
    </ol>
    <p>Note: Make sure your server-time is <a href="http://en.wikipedia.org/wiki/Network_Time_Protocol">NTP-synced</a>! Depending on the $discrepancy allowed your time cannot drift too much from the users' time!</p>
    <?php
    try {
        $tfa->ensureCorrectTime();
        echo 'Your hosts time seems to be correct / within margin';
    } catch (RobThree\Auth\TwoFactorAuthException $ex) {
        echo '<b>Warning:</b> Your hosts time seems to be off: ' . $ex->getMessage();
    }

**Comment by willpower232** [comment]
Its a different kind of exception and one that shouldn't be silenced. It seems the PHP software you're using doesn't have sockets installed so you will have to look up how to add them in.

**Comment by alve89** [comment]
I asked my provider if sockets can be enabled on my shared host - unfortunately this isn't possible. Is there another way 
1. to get rid of this error message and
2. to have the NTP sync anyway?

Perhaps I'm not the only one with this problem...

**Comment by willpower232** [comment]
I will include this situation in my documentation rewriting certainly.

Unfortunately you will not be able to use NTPTimeProvider as that is the one that requires sockets but you may be able to use another.

Your solution is to send a specific time provider to the function like this

```php
$tfa->ensureCorrectTime(array(new RobThree\Auth\Providers\Time\HttpTimeProvider()));
```

**Comment by alve89** [comment]
Great, thanks, it works properly now!
