### ISSUE TITLE
QRCode Redirect

### ISSUE THREAD

**Issue by mikegrahamjones** [RobThree/TwoFactorAuth#8]
Is there anyway to setup custom redirect for scanned QR Codes?

**Comment by RobThree** [comment]
Can you explain what you mean with "custom redirect"? This library does no redirects at all?

**Comment by mikegrahamjones** [comment]
I found a website [http://www.qrstuff.com/](QRStuff) where you can create a "QRCode" then have the Code redirect to a selected path.

I was wondering once a user scans the QRCode can it redirect somewhere e.g. 

**http://www.mywebsite.com/login_service/?secret=AUYWWBWM6SKQJZZ2&issuer=MyApp&period-30&alogrithm=SHA1&digits=6**

instead of how it currently just returns site data "opauth://topp/..."

![qrcode_result](https://cloud.githubusercontent.com/assets/923970/18258674/5d0e9c0e-742e-11e6-9bad-7ebe030d6f85.jpg)

**Comment by RobThree** [comment]
No, that's not how QR codes for 2FA work. You could easily change the source to include a URL but your app scanning the code would be the only one supporting/understanding it making the QR code incompatible with all other apps like Google Authenticator, Authy or LastPass Authenticator for example.

**Comment by mikegrahamjones** [comment]
Damn, that's okay, I was just interested in whether it would be okay without technical limitations. Thanks.

**Comment by RobThree** [comment]
YW 👍
