### ISSUE TITLE
Google / MS Authenticator

### ISSUE THREAD

**Issue by D4V3M0NK** [RobThree/TwoFactorAuth#81]
I write this hesitatingly as I'm not convinced that this is an issue with this code or not, but would like to throw out issues that we've started experiencing over the past few weeks. We use this library (1.7.0)to generate and authenticate using a QR code only but have experienced the following when using Google Authenticator (GA), Microsoft Authenticator (MA) and Duo (D).

1. If a user is using an Android phone, GA, MA and D all work flawlessly when presented with the QR code and entering the PIN.
2. If a user is using an IOS phone, then GA regularly has issues. MA and D work OK

Due to (2) we've been using both an IOS and Android based device to scan the same QR code, and using all three authenticators. The results are haphazard and don't appear to be following any logic, but we experience

1. Sometimes IOS with GA manages to scan the code without any issues at all
2. Sometimes IOS with GA scans the QR code but when entering in the same PIN as Android shows, the PIN gets rejected
3. Sometimes IOS with GA scans the QR code but shows a completely different PIN as the Android does

All servers have NTP configured and checks no more than every 30 sec intervals. The devices themselves are configured in the same timezone and we've confirmed that their system times are within 1sec of each other.

So - I'm at a bit of a loss.  I appreciate that we're not using the latest version but I find it odd that all of a sudden we've started seeing these issues. Yes I appreciate that it might be a problem with GA, but thought I would check in here first to see if this was a known issue (I didn't find anything) and there's nothing like getting advice from the horses' mouth, as it were.

**Comment by RobThree** [comment]
A few months later and I'm a bit hazy on what I meant with:

> But, anyway, yes, that's a very good suggestion and I'm a bit ashamed I didn't think of that first.

I'm not sure I was referring to upping the default discrepancy or something else. What are your opinions on what (if anything) we should do?

**Comment by D4V3M0NK** [comment]
@RobThree I've been keeping up to speed with my users about this, although at the moment I've not changed a thing on our application. Only one of the users that have reported issues actually had a device time issue - they had "update time" turned off on their iPhone. Even after updating their device, they experienced the same issues with Google's Authenticator. 

For all other users, we've advised that they use the Microsoft Authenticator or Cisco's Duo and thus far, with those apps, the users have experienced zero issues.

I'm not really sure where to go with all of this. Are you seeing any possible solutions from the other forums you're on?

**Comment by RobThree** [comment]
To be quite honest, the _only_ issues as far as I can remember have always been either PEBKAC or the time being incorrect in either the server or authenticator devices. None other that I can remember. Sorry.
