### ISSUE TITLE
endroid/qr-code compatibility issue

### ISSUE THREAD

**Issue by proxycheck** [RobThree/TwoFactorAuth#82]
Using the latest TwoFactorAuth (v1.8.1) works perfectly with Endroid/qr-code v3.9.7 but it breaks if you try to use a more recent version. For instance v4.3.5, v4.4.0 or the very latest v4.4.1.

The error given is this: 

`PHP Fatal error:  Uncaught Error: Class "Endroid\QrCode\ErrorCorrectionLevel" not found in vendor\robthree\twofactorauth\lib\Providers\Qr\EndroidQrCodeProvider.php:59`

**Comment by willpower232** [comment]
Thanks for letting us know, it looks like their website is either broken or missing right now so not sure how much code change will be needed. Will keep this on my to-do list to have another look for a changelog or upgrade guide in the future.

Unless of course someone more knowledgable than me with endroid makes a PR in the meantime 😅
