### ISSUE TITLE
Newly generated secrets failing to verify codes

### ISSUE THREAD

**Issue by matthewc83** [RobThree/TwoFactorAuth#87]
Hello,

I have been using your library in production for a couple of years now with no issue. We have had a bug come in where a user moving from non-2FA to 2FA could not get their code to verify. There is no issue with existing users verifying already set up codes.

I could reproduce this on production where neither the barcode nor the generated code would generate me an accepting code. I cannot reproduce it locally. I have also found that it works perfectly on our demo environment but the same problem occurs on our test/staging environment. 

All servers are running robthree/twofactorauth version 1.8.
All servers are running PHP 7.4 though there are minor differences between minor versions PHP 7.4.27  (ubuntu 18) where the issuing is occurring, PHP 7.4.14 (ubuntu 18), 7.4.16 (windows 10) where the problem doesn't appear.

I have tried swapping out IRNGProvider and constructing with HttpTimeProvider, all of which work beautifully on the already working environments but return false from TwoFactorAuth::verifyCode on the affected environments.

I am struggling to think what I could be missing, some php packages that are required but not installed on the affecting environments? I would have hoped that any changes in the way underlying PHP functions (thinking random_bytes) work would have bene ruled out by swapping out Providers.

Any thoughts on this appreciated or indeed any "this is not enough info! we require x,y and z to help"- I've not bothered with code samples since the codes does work on "good" environments and the code itself is consistent across the environments. I just can't think what environmental component I may be missing that would explain the behaviour of existing codes verifying but newly generated ones not.

**Comment by willpower232** [comment]
To confirm, you generate a secret successfully, store it in your app of choice but then cannot confirm that the codes that come out of that secret with the same code?

The most basic step is have you verified that the time is correct on all your servers?

**Comment by matthewc83** [comment]
Hi @willpower232 thanks for the reply. 
I generate the code successfully yes, it's the comparison to the users 6 digits that is failing on some servers.
I am thinking down the lines of time thing - though the servers all appear to report the same time, same timezone etc.

**Comment by willpower232** [comment]
I don't think timezone should matter, it would be whether the time down to the seconds is correct.

I'd hope you would get an exception or something if a dependency were missing. I guess you could compare the output of `php -i` from each server to be sure the environments were appropriately similar.

**Comment by matthewc83** [comment]
A diff between the outputs of php -i. I don't THINK I see anything obvious:
[diff](https://www.diffchecker.com/QTwtRUqJ)

**Comment by matthewc83** [comment]
Just thinking, if it was a server time thing - would it be expected that users with existing secrets have no issues? Wouldn't their codes be different from what the server is expecting?

**Comment by willpower232** [comment]
The diff looks fine although they have different image libraries so that might be annoying if you're generating QR codes. Although it could be mcrypt related maybe?

I guess the users devices need to have accurate time as well.

If one users secret works on a server and another users does not then the other users device time must be wrong or they entered the secret incorrectly.

**Comment by matthewc83** [comment]
Sadly already ruled out the QR code side by using the generated code rather than the QR code. 
also ruled out user device based on it being my device working against some environments and not others.
I guess I'll keep at it - probably something stupid that is escaping me.

**Comment by willpower232** [comment]
You can see that in spite of mcrypt, it still uses random_bytes where possible https://github.com/RobThree/TwoFactorAuth/blob/e76f31e93bab7c6ec3c87104c593837729a6c7d8/lib/TwoFactorAuth.php#L333-L335

You could ensure that the function is available on both servers to narrow it down.

**Comment by matthewc83** [comment]
Yeah, I have put some debugging around that before I started swapping out providers - they were all using CSRNGProvider() by default

**Comment by willpower232** [comment]
Hmm definitely a mystery. I guess you could also verify that the secret being passed to the library was absolutely identical although if it was different then that would be even weirder.

**Comment by matthewc83** [comment]
I'll dig away - I am wondering if it's somehow something to do with infrastructure that is more complex is in prod/staging vs local and demo. I am pretty positive it's going to come down to "my" error somewhere - I'll report back if/when I figure it out! Cheers for the input thus far, even knowing it's not something obvious is good to know.

**Comment by matthewc83** [comment]
Hey, just to confirm this does indeed fall under "user error"  - no surprises there. A change meant that in actual fact 2 codes were being generated in some environments with the "wrong" one being returned to the user thus never being able to be verified. 

Thanks for the suggestions, apologies for the time wasting!

**Comment by willpower232** [comment]
No worries, glad you figured it out! Thanks for letting us know
