### ISSUE TITLE
How i can generate Backup 2fa after user has been activated 2fa

### ISSUE THREAD

**Issue by THESPIKEONE** [RobThree/TwoFactorAuth#88]
like on the 2fa system from epic games when you activate your 2fa it gives you backup codes 
how can i do that ?
thanks

**Comment by RobThree** [comment]
You just generate some random strings/codes and store them with the useraccount. This is not something this library provides (you _could_ use (part of) the output of the `createSecret()` method to generate some backup codes I guess).

**Comment by THESPIKEONE** [comment]
Ah okay can you show me a code how to do that  ?  i would generate 6 back up code

**Comment by RobThree** [comment]
Use a for-loop or something? The basics are:

1. Generate X-number of codes using `createCode()` or any other means to generate a [random string
2. ](https://www.php.net/manual/en/function.random-bytes.php)
3. Show codes to user
4. Store codes in database or whatever  

This is all highly dependent on your code, your environment, everything. There's no "THE" way to do this, there's infinite ways to do this (some better than others, ofcourse). But please understand that github issues are not a support forum for general programming questions. You might want to try [stackoverflow](https://stackoverflow.com/) or similar sites for that.

**Comment by willpower232** [comment]
I would suggest using something like `bin2hex(random_bytes(10))` to create the secrets and then use whatever password hashing algorithm from the framework in use to store them securely.

**Comment by THESPIKEONE** [comment]
okay thank you for your help
