### ISSUE TITLE
Why key can validate multiple use ?

### ISSUE THREAD

**Issue by parnus01** [RobThree/TwoFactorAuth#9]
when i validate key and success login , after i logout why it can use same key to validate 

How can i implement it to expire key now after validate success.

thnak you

**Comment by RobThree** [comment]
Thats how TOTP works... Each code is valid for a certain period (usually a 'window' of 30 seconds +/- 1 (or more periods either way) so in effect each code is (by default) valid for ~90 seconds.

> ... For this to work, the clocks of the user's device and the server need to be roughly synchronized (the server will typically accept one-time passwords generated from timestamps that differ by ±1 time interval from the client's timestamp). A single secret key, to be used for all subsequent authentication sessions, must have been shared between the server and the user's device over a secure channel ahead of time. If some more steps are carried out, the user can also authenticate the server using TOTP. ([Source](https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm))

The period length (30 seconds) and number of intervals may differ and can both set (`$period` in the constructor and `$discrepancy` in the `verifyCode()` method). But not all "authenticator apps" support periods other than 30 (or multiples of seconds).

> How can i implement it to expire key now after validate success.

Codes "expire" every (in the example above) 90 seconds (with a period of 30 s and T±1 interval). If you want to prevent a replay-attack (or "expire" a code immediately) you should store the last login timeslot (UNIXTIME modulo `period`) and disallow new logins in that same timeslot±X intervals. On how to do that; that's up to you. You could store it in a database, file, whatever...

**Comment by parnus01** [comment]
ok,i understand and How i can  reduce time to expire (90 seconds) to 30 or 60 ?

iam try to chage $discrepancy it not work

**Comment by RobThree** [comment]
> How i can reduce time to expire (90 seconds) to 30 or 60 ?

Please read the [README](https://github.com/RobThree/TwoFactorAuth/blob/master/README.md) and above explanation. You can use `$period` and `$discrepancy` and both work exactly as documented.

> iam try to chage $discrepancy it not work

Please tell me **how to reproduce** (i.e. what you did/do exactly, what "not work" means). Are you **sure** you're implementing it correctly and have understood how this all works? Opening an issue and complaining "iam try to chage $discrepancy it not work" after an (extended!) explanation of what is, essentially, also in the README is not the way to go; please show a little more effort on your behalf.

**Comment by parnus01** [comment]
i just change $discrepancy = -4 but it same90 seconds

**Comment by RobThree** [comment]
What made you think a `$discrepancy` of -4 would work?
The smallest discrepancy is 0. If anything, this library should throw on negative discrepancies...

The `$discrepancy` argument is the number of timeslices checked (to either side) of the current timeslice. So:

| **Discrepancy** | **Checked (or "valid") timeslices** |
|-----------------|------------------------------------------------|
| 0 | `T0` |
| 1 (default) | `T-1`, `T0`, `T+1` |
| 3 | `T-3`, `T-2`, `T-1`, `T0`, `T+1`, `T+2`, `T+3` |

**Comment by parnus01** [comment]
ok if iwant 30 to expire set $discrepancy and not concern $peroid ?

**Comment by RobThree** [comment]
> ok if iwant 30 to expire set $discrepancy=0 and not concern $peroid ?

Your question is unclear but from what I understand from it I'm pretty sure the answer is yes, pass `0` to the `$discrepancy` argument and keep `$period` default (or set it explicitly to `30`). Again; this should be clear if you read the README (and/or my earlier posts in this thread).
