### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by AlexanderSchaller** [RobThree/TwoFactorAuth#90]
The composer file says version 1.8.1 while your release on GitHub says version 1.8.2.  I'm not actually able to update the dependency in my composer to fix some issues with php 8.1 (which I see 1.8.2 fixes)

**Comment by AlexanderSchaller** [comment]
Thank you so much!

**Comment by willpower232** [comment]
@RobThree I've moved the tag but I'm not sure how packagist is set up, are you able to see any issues? It reckons its set up for auto updating

**Comment by RobThree** [comment]
Should be fixed now. Please let me/us know if there's still an issue.

**Comment by willpower232** [comment]
Thanks for resolving, it turns out that we shouldn't be referencing the version in composer.json because the github tags/releases should take priority https://getcomposer.org/doc/02-libraries.md#library-versioning

Am I okay to remove the version reference from composer.json?

**Comment by RobThree** [comment]
Sure, go ahead 👍
