### ISSUE TITLE
How to migrate to new server

### ISSUE THREAD

**Issue by Tsjippy** [RobThree/TwoFactorAuth#96]
I have migrated my website to a new server.

Now the 2fa verification always fails (verifyCode returns 0);

How can I find out why and how to solve it?
I don't want all my users to set it up again....

What changed:
Moved from php 7.4 to php 8.0.25
Moved from utf8 to utf8mb4
Moved to a different timezone

**Comment by RobThree** [comment]
99% sure the time on the server is off (or off on the previous one).

**Comment by Tsjippy** [comment]
Can I adjust the time in the database ? Or should I change the time on the server?

**Comment by RobThree** [comment]
I don't know what time in your database would be related to this? If you check the actual time on the server(s) you'll most likely see one of them is off.

**Comment by RobThree** [comment]
By default, this library uses [`time()`](https://github.com/RobThree/TwoFactorAuth/blob/ba4e8c55ed150da31b92ce68ac93659926d8b3a4/lib/Providers/Time/LocalMachineTimeProvider.php#L9), which, according to the PHP doc, returns a [Unix Timestamp](https://www.php.net/manual/en/function.time.php). which is UTC time. So either you used a different timeprovider or your timezones aren't configured correctly.

**Comment by Tsjippy** [comment]
I have changed the timezones, now they are in the same timezone, still doesn't work

**Comment by RobThree** [comment]
Try [`ensureCorrectTime()`](https://github.com/RobThree/TwoFactorAuth/blob/master/demo/demo.php#L44).

**Comment by willpower232** [comment]
in bash you can do `date +"%s"`

![image](https://user-images.githubusercontent.com/1619102/205098243-f007a04e-ca76-4abf-baf4-336e3b0483f7.png)

and then compare the output to https://time.is/Unix_time to confirm the values are the same or within a few seconds

**Comment by Tsjippy** [comment]
Thanks both for your replies!
It works again

**Comment by RobThree** [comment]
> Thanks both for your replies!
> 
> It works again

Please share with us what the issue was?

**Comment by Tsjippy** [comment]
I think it was a time issue. I changed the time zone and now it works ok
